= Administrator Tasks
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Exchange administrators have permissions to perform these tasks:

* xref:to-share-an-asset.adoc[Share an asset]
+
Share an asset to publish an API asset to a public portal, or to grant access to an asset to specific users in your organization, to everyone in your organization, or to everyone in a chosen external organization.
* xref:to-share-api-asset-to-portal.adoc[Publish an API to a public portal]
+
Publish APIs to a public portal for external users.
* xref:to-save-searches.adoc[Save searches]
+
Save and maintain searches for assets within a business group.
* xref:to-enable-the-request-access-button.adoc[Use API Manager to add the Request Access button]
+
Specify which API assets can be shared with users.
* xref:to-set-permissions.adoc[Set User Access Permissions]
+
Grant the Exchange Administrator, Contributor, Viewer, or Creator permissions to members of your organization, and optionally provide access for individual assets.
* xref:cookies.adoc[About Exchange cookies]
+
Find information about Exchange cookies, cookie configuration, and cookies for vanity domains.
* xref:migrate.adoc[Migrate Exchange 1 assets to Exchange 2]
+
Move assets from Exchange 1.
