= Document an API
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Anypoint Exchange lets you create API Notebooks which let you describe each function in your API and provide a test area so that users can experiment with sending different values to the API and receiving output.

my fine new edit

After creating your API Notebook you can optionally create an API instance to control whether the notebook is private or public. By setting the notebook's instance to private, others in your organization can review it. When you are ready, you can set the API instance to make the API Notebook public.

Note: API Notebooks are independent of the use of an API instance.
If you don't use a base URI in your RAML, or use an API instance, you can use the mocking service to generate test data.

Topics:

* xref:to-use-api-notebook.adoc[To Document an Asset Using API Notebook]
* xref:to-configure-api-settings.adoc[To Configure API Instances]

== See Also

* xref:to-describe-an-asset.adoc[To Describe an Asset]
