= Autocatalog APIs Using API Catalog CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

API Catalog CLI enables you to catalog your API specifications, documentation files, and associated metadata as part of an automated process. You can embed the publish asset command in your automation tools, such as a CI/CD pipeline or custom scripts, to automatically trigger the cataloging of your API assets. API Catalog CLI is agnostic of CI/CD tools and runtime environments.

[get-started]
== Get Started with API Catalog CLI

To get started with API Catalog CLI: 

. Ensure MuleSoft has enabled the API Catalog entitlement for your Anypoint Platform organization.
. xref:install-api-catalog-cli:install-api-cat[Install] the API Catalog CLI.
. xref:configure-api-catalog-cli:install-api-cat[Configure] required catalog permissions.
. xref:create-descriptor-file-cli:create-desc-file-cli[Create a descriptor file] to identify the APIs to publish.
. xref:publish-using-api-catalog-cli:publish-apis[Catalog an asset] using the API Catalog CLI and view it in Anypoint Exchange.

TIP: Consider testing the process end-to-end locally before integrating it into your CI/CD pipeline or custom scripts. 

// == See Also

// * xref:anypoint-platform-cli-commands.adoc[Anypoint Platform CLI List of Commands]
