= Snapshot Assets
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In Anypoint Exchange, a snapshot asset represents an asset that can be republished over and over again.


== Create a Snapshot Asset Version

To create a snapshot asset you only have to add the `-SNAPSHOT` suffix to the asset version. For example: `1.0.0-SNAPSHOT`.

A snapshot can be created through Exchange manual publication, Design Center, API Manager, Studio, directly from the Exchange API, or using the Maven Facade.

No changes are required to republish a snapshot, republishing is the same as publishing the first time.


== Publish a Snapshot Asset Version

* Although a snapshot version can be listed in the Exchange private portal, it cannot be listed in a public portal. So, snapshot asset versions are not shown in a public portal.
* When you create the release version such as `1.0.0` of a snapshot version (`1.0.0-SNAPSHOT`), the snapshot version is no longer usable in Exchange.
* When asking for assets through the Exchange graph service, it doesn't retrieve the snapshot versions as default. To include them, add the property: `includeSnapshots: true`. To find more information, see the `See Also` section.
* When creating a REST API snapshot version, connectors generated by REST Connect automatically are versioned with SNAPSHOT.


== Republish a Snapshot Asset Version

* A new portal for the snapshot version won't be created, so its portal is the one that was created the first time.
* Asset version dependencies, tags, permissions and any other asset metadata aren't modified when the version is republished.
* If a new file has been created as part of the snapshot version, its the only file of the version and the files of the previous snapshot version no longer exist any more.
* If the asset is a REST API, the OAS or RAML translation is translated again and the connectors created by REST Connect are generated again too.


== See Also

* xref:to-create-an-asset.adoc[Publish an Asset to Exchange].
* xref:to-search-with-graph-api.adoc[Search with Graph API].
