= Administrator Tasks
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Exchange administrators have permissions to perform these tasks:

* xref:to-share-an-asset.adoc[Share an asset]
+
Grant access to an asset to a user in your organization, to everyone in your organization, or to everyone in a chosen external organization, or publish an API asset to a public portal.
* xref:to-save-searches.adoc[Save searches]
+
Save and maintain searches for assets within a business group.
* xref:to-enable-the-request-access-button.adoc[Use API Manager to add the Request Access button]
+
Specify which API assets can be shared with users.
* xref:to-deprecate-asset.adoc[Deprecate an asset]
+
Remove access to a version of an asset but keep other versions of the asset available to users.
* xref:to-set-permissions.adoc[Set Exchange role permissions]
+
Grant Exchange administrator, contributor, or viewer permissions to members of your organization, and optionally provide role access for individual assets.
* xref:cookies.adoc[Configure cookies]
+
Enable cookie configuration for website visitors, and if you use a vanity domain, enable cookie configuration for the vanity domain.
* xref:migrate.adoc[Migrate Exchange 1 assets to Exchange 2]
+
Move assets from Exchange 1.
