= Exchange Public Portals
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Exchange public portals are available on the internet to everyone and enable outside developers to access an organization's REST, SOAP, and HTTP APIs.

Exchange portals replace what used to be known as a Developer Portal.

You can customize the look and content of the portal with a logo, banner image, text, and a favicon for the browser tab.

== Share an Asset or Update the Asset Description

Exchange Administrators can share an API asset to a public portal.

. Locate the asset in your organization's Exchange.
. Edit the asset's description, and when done, publish the asset.
. Return to the portal and click the asset. The description updates automatically after changing the description in the asset.

== Users From Other Anypoint Organizations

Users can view a public portal without logging in, and must log in to use features such as reviewing assets, downloading assets, creating a client application to request API access, and accessing an API.

Users from other Anypoint Platform organizations can use your public portal to register client applications so they can access your APIs. Because they do not belong to your organization, they are external users of your organization's portal.

An organization administrator can see only the basic profile of an external user, which contains only this information:

* Name
* Username
* Email
* Primary organization name

The first time an external user logs in to your public portal, the portal requests permission for read-only access to this basic profile. When the user approves the request, they are added in the Anypoint Platform tab *Access Management* > *Users* > *External Users*. As your organization's administrator, you can enable or disable each external user on that tab. Disabled external users cannot sign in to your public portal.

To grant an external user permission to perform tasks such as deploying an application, invite the user to join your organization.

== See Also

* xref:to-customize-portal.adoc[Customize an Exchange Public Portal]
* xref:portal-vanity-domain.adoc[Public Portal Vanity Domain]
