= Autocataloging APIs Using API Catalog CLI

API Catalog CLI enables you to discover and catalog your API specifications, documentation files, and associated metadata as part of an automated process. You can embed the publish asset command in your automation tools, such as a CI/CD pipeline or custom scripts, to automatically trigger the cataloging of your API assets. API Catalog CLI is agnostic of CI/CD tools and runtime environments.

API Catalog CLI:

* Identifies all API assets in a project directory structure and creates a descriptor file to use to publish the API assets to Exchange.
* Enables you to conditionally trigger the publish based on criteria such as branches and tags.
* Enables you to conditionally set the asset version strategy based on criteria such as branches and tags.
* Publishes assets described in the descriptor file locally or as part of your automation tools.
* Updates the descriptor file with new and changed API information. 

[[get-started]]
== Get Started with API Catalog CLI

To get started with API Catalog CLI: 

. Ensure MuleSoft has enabled the API Catalog entitlement for your Anypoint Platform organization.
. xref:install-api-catalog-cli.adoc[Install] the API Catalog CLI.
. xref:configure-api-catalog-cli.adoc[Configure] required catalog permissions.
. xref:create-descriptor-file-cli.adoc[Create a descriptor file] to identify the APIs to publish.
. xref:publish-using-api-catalog-cli.adoc[Catalog an asset] using the API Catalog CLI and view it in Anypoint Exchange.

TIP: Consider testing the process end-to-end locally before integrating it into your CI/CD pipeline or custom scripts. 

== See Also

* xref:4.x@anypoint-cli::anypoint-platform-cli-commands.adoc[Anypoint Platform CLI List of Commands]