= Publish APIs Using API Catalog CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

== API Catalog CLI

API Catalog CLI enables you to publish APIs to Anypoint Exchange as they are created and updated as part of your CI/CD processes. 

With API Catalog CLI you can:

* Publish API specifications in Exchange using CLI commands 
* Use descriptor files to explicitly define how you want the specifications to be published

For details, see the following:

* <<Install API Catalog CLI>>
* <<Descriptor Files>>
* <<Publish APIs Using CLI>>

== Install API Catalog CLI 

To enable developers in your organization to automatically publish the new API specifications, you must install API Catalog CLI and add it to your CI/CD pipeline. 

=== Prerequisites

* Download and install NodeJS and npm (node package manager) on your system.
+
See the https://nodejs.org/en/download/[NodeJS download page].
* Download and install the Git version management on your system.
+
See the https://git-scm.com/downloads[Git download site].

Depending on the configuration of your system, you might need to run these commands using administrator credentials.

[source,text,linenums]
----
$ npm install -g anypoint-cli@latest
----

If the installation command fails with the following error, ensure that the Git client is installed on your computer and the git protocol is not blocked by your firewall or network:

[source,text,linenums]
----
fatal: read error: Invalid argument
----

If the git protocol is blocked, you can configure Git to use `https://` instead of `git://`:

[source,text,linenums]
----
git config --global url."https://".insteadOf git://
----

System Requirements:

* Anypoint Platform account
* Anypoint Platform user account

=== Install the CLI

To install the CLI:

. Download the API Catalog CLI package from the https://npmjs.com[npm public registry]. 
. Run the following command from your terminal, where <API-Catalog-CLI-package-name> is the name of the package you downloaded:
----
npm install -g <API-Catalog-CLI-package-name>@beta
----

=== Make the CLI Available From Any Directory

Use the following command to make the API Catalog CLI command available from any directory:

----
$ npm link
$ cd ../<your-directory-name>
$ api-catalog-cli publish-asset
----

=== View Command Help

Use the help argument with the commands to list the commands or command arguments and their descriptions:

* +api-catalog --help+
* +api-catalog autocomplete --help+
* +api-catalog create-descriptor --help+
* +api-catalog publish-asset --help+

=== Configure and Use Autocomplete

Before you can use the autocomplete command, you must add it into your shell profile.

To add autocomplete to a bash shell profile:

* If your terminal does not start as a login shell, enter the following command:
+
+$ printf "eval $(api-catalog autocomplete:script bash)" >> ~/.bashrc; source ~/.bashrc: value+

* If your terminal starts as a login shell, enter the following command:
+
+xxx+

To add autocomplete to a Z shell profile:

* +xxx+

==== api-catalog autocomplete

After you have added the command to your shell profile, you can run it with arguments to control the results.  

----
> api-catalog autocomplete [arguments] 
----

This command enables you to use the tab key to autocomplete a partially-typed api-catalog command. 

[%header,cols="30a,30a"]
|===
| Argument | Description 

| bash | Use the bash shell.  

| zsh | Use the Z shell.    

| --refresh-cache | Clear the cache.  

|===

==== Using Autocompletion for api-catalog Commands 

After you have installed the plug-in into your shell, use the command as follows: 

+$ api-catalog <TAB><TAB>                 # Command completion+

+$ api-catalog command --<TAB><TAB>       # Flag completion+

== Descriptor Files

Before you run the commands to publish your APIs, you must create a descriptor file in each of the Git repositories you are using for your CI/CD processes. You can use the following approaches:

* *Dry Run Mode*: Use this mode to run the publish catalog command with an empty descriptor.yaml file and get a preview in your CI/CD log of the APIs that would be cataloged. 
* *Explicit Mode*: Use this mode to run the publish catalog command with a complete descriptor file that specifies the APIs that should be cataloged. 

=== Prerequisites

Before you add the descriptor file to the repository, ensure that:

* The API Catalog CLI is installed on a computer in your CI/CD pipeline. 
+
See <<Install the CLI>>. 
* You have the repository location where you want to add the descriptor file ready.

=== Dry Run Mode

Use dry run mode to generate content for a starter descriptor file and discover which APIs are available in a CI/CD repository that are candidates to be cataloged in Exchange. The CI/CD job sends results to standard output. The output has suggested descriptor file content and status messages, such as lists of APIs that would not be cataloged based on this descriptor content.
No API specifications or documentation are cataloged in Exchange.

To use dry run mode:

. Add an empty +descriptor.yaml+ file to your Git repository. 
. Modify your CI/CD pipeline to add the following command: 
+
+api-catalog publish-asset --dry-run=dry-run+
+
See <<Publish APIs Using CLI>> for command details.
. Run the CI/CD pipeline.
. Check your CI/CD log for the results.
. Update the +descriptor.yaml+ file in your Git repository with the content from the dry run and modify as needed. 

=== Explicit Mode

Use explicit mode when you have descriptor file content that identifies the APIs that you want to publish in Exchange. You can use dry-run mode to obtain suggested content from your CI/CD repository or you can create the descriptor file by using the following documentation. 

=== Create a Descriptor File

The +api-catalog create-descriptor+ command parses the YAML schema that describes the APIs to catalog. The results are stored in a descriptor file that is then used by the +api-catalog publish-assets+ command to publish identified APIs to Exchange. See <<Publish APIs Using CLI>>.

==== api-catalog create-descriptor

----
> api-catalog create-descriptor [arguments] 
----

*Arguments*

+-f, --file=file+
  +
  [default: +catalog.yaml+] 
  + The name and location in which to save the generated catalog descriptor file.

== Descriptor YAML Schema

Following are the YAML tags used to describe the APIs you want to catalog. 

[%header,cols="40a,30a,30a"]
|===
| Tag | Description |  Default

| branches | Specifies the branches from which to pull API information to be cataloged.  |
master

| apis | A list of the APIs to be cataloged. |  N/A

| spec | The location of the specification file that describes the API. | N/A  

| asset-id | Specifies the ID of the asset to be published in Exchange. | By default, this ID is generated from the API specification *Title* field.  

| docs   | A list of key and value pairs that specify the name of the documentation page and file location for the API.
These pairs define the order of the documentation pages in Anypoint Platform. +
Example: <Name of the Doc Page>:<File Location> | NULL. If not specified, no Doc pages will be imported. 

| tags  | A list of comma-separated xxx text strings to describe the API. These appear on the asset's page in Exchange. xxx  +
Example: xxx, xxx, xxx | NULL. If not specified, no tags will be added.

| categories | A list of key and value pairs that specify the category name and value. These pairs are validated against the categories that exist in the Anypoint Platform organization. +
Example: <Category Name>: <Value(s)> | NULL. If not specified, no categories will be added.

| custom-fields| A list of key and value pairs that specify the field and value. These pairs are validated against the custom fields and field types that exist in the Anypoint Platform organization. +
Example: <Field>: <Value> | NULL. If not specified, no custom fields will be added.

| versioning | xxx | xxx

| apiVersion | xxx | xxx

|===

Although you can enter authentication credentials explicitly in the commands for testing purposes, you should use secure authentication in your CI/CD environment.

See <<Authentication>>.

=== Example Descriptor Files 

Following are some examples of typical descriptor files.

==== Example 1: Descriptor file that describes two APIs

Following is a descriptor file that describes two APIs to catalog. The cataloging will be done by a subsequent run of the related +api-catalog publish-asset+ command. 

//The following descriptor file results in the following:

//* xxx branches are
//* xxx tags are
//* xxx user is
//* codat API is published as follows:
//** xxx
//** xxx
//* billing API is published as follows:
//** xxx
//** xxx

---

 #%Catalog Descriptor 0.5
 triggerConditions:
   branches:
     - master
     - release/(.*)
   tags:
     - support
     - release/(.*)
   user:
     - admin

 contact:
  name: 'John Doe'
  email: 'john.doe@org.com'

 apis:
  - spec: api-spec/codat.json
    assetId: codat-api
    docs:
      add: api-spec/add.md
      home: home.md
    customFields:
      custom: value
      another: field
    tags:
      - codat
      - gcp
    healthCheck:
      url: https://dev.codat.io/api/ping
      method: GET
      expectedStatus: 204
    versioning: 2.0.x
    apiVersion: v3 
    - spec: api-spec/billing-api.json
      assetId: my-awesome-api
      tags:
       - finance
       - aws
     categories:
       API Type:
        - System API
        - Experience API
      Organization:
        - Finance
        - Billing
     healthCheck:
       url: https://billing.io/api/health
     versioning: ~1.x.x
     apiVersion: v1

---

*After publication in Exchange*

xxx include a screenshot of this example after publication in exchange xxx

==== Example 2: Generate a descriptor file after autodiscovering API candidates

Use the dry-run Argument with the publish-assets command to generate a catalog.yaml file after autodiscovering all API candidates. xxx 

==== Example 3: Section that defines the documentation, contacts, and other API metadata 

- Catalog Descriptor section clarifying how to set up documentation, contacts, and other API metadata

==== Example 4: Section that defines the version strategy 

- Specific section on how to define the versioning strategy in the Descriptor (strategy + version selection)

*Specify the Version Rules*

<...>  
// text relevant to versioning

Metadata is mutable for a given major version. The process of cataloging an asset includes not only the API specification itself, but also documentation (portal pages) and asset metadata (contact, categories, tags, and so on). The metadata is associated with the current major + minor version of the asset. Therefore, all assets for the same minor version in Exchange will share the same metadata. The metadata cannot be considered immutable for a given major version, as metadata for a newer asset for the same minor version will overwrite it. 
//


== Add the Descriptor File to Your API Project Location

After you install API Catalog CLI, you must add the descriptor file, with the file name and location specified by your DevOps admin, to the location of the API project that you want to integrate with the publishing process.

*Prerequisites*

Before you add the descriptor file to the API project, ensure that:

* API Catalog CLI is installed in a location accessible by your CI/CD pipeline. For details on how to perform this installation, see <<Install the CLI>>. 
* The API project location is accessible by your CI/CD pipeline.
* The API project contains APIs supported by Anypoint. 

To add a descriptor file to an API project:

* Copy the descriptor file, such as +catalog.yaml+, to the file path or repository where your API projects are stored. 

== Publish APIs Using CLI
You can publish your APIs to Anypoint Exchange with API Catalog CLI commands. To automate the publishing of APIs using CLI, you will typically use build scripts in tools such as Jenkins, but you can run the CLI manually from a terminal for learning and testing purposes. 

=== api-catalog publish-asset

----
> api-catalog publish-asset [options] 
----

This command publishes APIs to Exchange using the descriptor information passed in the YAML file passed in the catalog-file option.

ƒ
[%header,cols="40a,30a,30a"]
|===
| Argument | Description |  Example

| -a, --anypoint-uri=anypoint-uri 

or

ANYPOINT_BASE_URL environment variable

 | (Required) 

Default: https://anypoint.mulesoft.com

The Anypoint Platform base 
URL. It must be specified using HTTPS protocol. |
For the US Anypoint Platform, use  
+https://anypoint.mulesoft.com/+. 

|  -c, --catalog-file=catalog-file 

or

ANYPOINT_CATALOG_FILE environment variable

 | Default:  ./catalog.yaml 
 
The name and location of the catalog descriptor file.  

  * If the file does not exist, no cataloging will be performed.
  * If the file exists, but is empty, the command will scaffold and print the catalog descriptor based on all specifications in the full directory tree relative to the current working directory.
  * For additional control, you can declare what to catalog and how. | See <<Descriptor Files>>.

| -d, --dry-run=dry-run  | Runs the command to identify the APIs that are eligible to be published. No APIs will be published. The descriptor file specified in the catalog-file Argument defines the scope. |   

| -o, --organization=organization 

or

ANYPOINT_TARGET_ORGANIZATION environment variable

  | (Required) 
  
The ID of the Anypoint Organization where the APIs will be cataloged.  | 

| -p, --password 

or

ANYPOINT_PASSWORD environment variable

 | Prompt Anypoint password for username. Set the environment variable to avoid the prompt for the password.   | See <<Authentication>>.

| -s, --silent | Turn on silent logging.|

| -t, --trigger=branch:master --trigger=tag:bla  | User-defined filters that are applied to the descriptor file to determine whether an asset should be published. |  

---

 triggerConditions:
 branch:
   - master
   - test/(.*)
 tag:
   - release
   - hotfix

---
  

    





| -u, --username=username 

or

ANYPOINT_USERNAME environment variable

| Anypoint username.  | See <<Authentication>>.

| -v, --verbose | Turn on verbose logging. |



| --async |  Run the publish job asynchronously. |

| --client-id=client-id 

or

ANYPOINT_CLIENT_ID environment variable

| Connected App client ID.  |

| --client-secret 

or

ANYPOINT_CLIENT_SECRET environment variable

 | Prompt for the Connected App secret for client-id. Set the environment variable to avoid the prompt for the client secret.  |

 | --force-publish |  Bypasses the comparison and 
 creates a new version of the asset in Exchange regardless of the content.|

| --force-update-metadata | Forces update of the asset's metadata (such as tags) in the latest version in Exchange regardless of the content. |

| --json | Prints the execution result in json format. |

|===

=== Specify the Version Rules

When you publish an API to exchange, the patch version is incremented by default. However, you can set the version using a combination of the API and asset version Arguments as follows:

xxx table with the settings and examples from the video xxx 

For more information on API and asset versioning in Exchange, see xref:to-change-raml-version.adoc[Change the Version of an API Asset].

For information on passing credentials, see <<Authentication>>.

=== Example Publish Asset Commands

Following are examples that show some typical use cases for publishing assets.

==== Example 1: Publish an asset with default settings

The following example publishes the API to the ‘4c06ba7b-3ce8-425c-878c-b728dd7db60d’ organization in the US control plane using the ./catalog.yaml descriptor file in the master branch of the VCS repository:

api-catalog-cli publishAsset -o c06ba7b-3ce8-425c-878c-b728dd7db60d  -a https://anypoint.mulesoft.com/

In the example, an assumption is made that either the username and password credentials are defined in the ANYPOINT_USERNAME and ANYPOINT_PASSWORD environment variables or that the client ID and client secret credentials are already defined.

==== Example 2: Publish an asset using the trigger filters 

// Triggering and Filtering Text

Custom trigger and filter conditions enable you to further control what is published when the API Catalog CLI command runs. 

To use trigger conditions:

 (--trigger Argument)

// More info can be found here:
// https://docs.google.com/document/d/1j31ANa7hQpJ9X2PCLDxZXUrFK42qPjng9jGstNBBSX4/edit

// end of Triggering and Filtering text

==== Example 3: Publish an asset using the force-publish Argument
// Force Publish Text
Forcing (Diffing Bypass)

When attempting to catalog an API spec, we should do our best effort to determine whether or not the asset in Exchange corresponds to the same content of the developer environment and avoid duplicating assets when not necessary. 

There might be cases when the user wants to publish a new asset, even when API spec content has not changed. For those cases, the CLI will provide a --force-publish flag Argument that will indicate the tool to bypass the comparison and always create a new version in Exchange, regardless of the content.

If the same version of an API exists but you still want to create another asset, you will need to use the force publish command.

Forcing (Metadata Update)
There might be cases when the user wants to update the metadata, even when API spec content has not changed. For those cases, the CLI will provide a --force-metadata-update flag Argument that will indicate the tool to update the asset metadata, regardless of the API spec content. 


//publish errors/skip cases for our clients to be able to solve them.
//For example, understanding the case in which the CLI skips the publication since the API content is exactly the same as the latest published version in Exchange. We may also want to document the "force-publish" Argument to be able to bypass this CLI restriction in case clients still want to publish a new identical version.//

// end Force Publish Text

==== Example 4: Do a dry run to see assets that are eligible to publish

// Other example cases text

This example shows a publish-asset command with the following:
* "dry-run" Argument: Identifies the eligible APIs to publish but does not actually publish them
* "result" Argument: Captures the results
* "verbose" Argument: Shows the maximum information in the results

xxx example code goes here xxx

// 

== Example Jenkins Script 

An example Jenkins script that runs the commands is as follows:

<Example Jenkins script>

== Authentication

You can configure Anypoint CLI authentication with username and password, client ID and client secret, or a bearer token.
At least one method is required.

=== Username and Password

If you don't log in using single sign-on (SSO), you can use your username and password to log into the CLI directly.

[%header%autowidth.spread,cols="a,a"]
|===
| Argument | Description
| `username` | Your Anypoint Platform username

You can also pass this value using the environment variable `export ANYPOINT_USERNAME=<name>`.
| `password` | Your Anypoint Platform password

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>`.
|===

For information about logging in using SSO, see xref:access-management::external-identity.adoc[About Identity Management].

=== Client ID and Client Secret

You can configure a Connected App with the `client_credentials` grant type to use with the CLI.

[%header%autowidth.spread,cols="a,a"]
|===
| Argument | Description
| `client_id` | The ID of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_ID=<client_id>`.
| `client_secret` | The client secret of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_SECRET=<client_secret>`.
|===

// For more information about Connected Apps, see xref:access-management::connected-apps-overview.adoc[Connected Apps].

=== Environment Variable Usage

Keep the following in mind while using API Catalog CLI:

* Command-line Arguments override environment variables. +
If you don't pass a command-line Argument, the default profile properties are used.
* If not specified, the default environment is production.

=== Timeout

Your Anypoint session expires based on the *Default session timeout* configured in your Master Organization settings.

// Authentication end 

// == See Also

// * xref:anypoint-platform-cli-commands.adoc[Anypoint Platform CLI List of Commands]
// Anypoint Exchange
