//Use the MultiTopic template to document subjects that include a combination of topic types. This template includes all three topic types. Remove topic types that aren’t needed, or add additional topic types when needed. 

= Publish APIs Using API Catalog CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

== API Catalog CLI

API Catalog CLI enables you to publish APIs to Anypoint Exchange as they are created and updated as part of your CI/CD processes. 

== What You Can Do With API Catalog CLI

With API Catalog CLI you can:

* Publish API specifications in Exchange using CLI commands 
* Use descriptor files to explicitly define how you want the specifications to be published

== Install API Catalog CLI 

To enable developers in your organization to automatically publish the new API specifications, you must install API Catalog CLI and add it to your CI/CD pipeline. 

System Requirements:

* Anypoint Platform account
* Anypoint Platform user account

== Install the CLI

To install the CLI, run the following commands from your terminal using the link provided to you:

----
npm install -g <path to tar, such as api-catalog-cli-0.3.7.tgz> 
----

<more from Readme, POC doc, product>

== Give Access to the CLI from Any Directory

Use npm link to have the CLI available from any directory:

----
$ npm link
$ cd ../some-test-directory
$ anypoint-cataloging-cli publish-asset
----

== Create a Descriptor File

Before you run the commands to publish your APIs, you must create a descriptor file. <copy in the information on this from the readme and reorganize and edit as needed> 

If you create an empty descriptor file, you will initiate the CLI in Convenience Mode. This mode requires no additional work from your end, but has some limitations. Conversely, you can use the Explicit Mode of the CLI for more control over the implementation of the descriptor file.

=== Convenience Mode

If your repository contains an empty descriptor file in the correct location, the CLI attempts a best-effort approach to determine which API specifications in your repository must be published.

If the API Catalog CLI publishAssets command is run and no descriptor file is found, an empty default file is created with the name <tbd>. 

<more from Readme, POC doc, product>

=== Explicit Mode

For additional control over the publishing process, you can specify which attributes or other details of the API specification must be explicitly published. The descriptor file contains this specification to be consumed by the CLI.

*Syntax*

<...>

Although you can enter authentication credentials explicitly in the commands for testing purposes, you should use secure authentication in your CI/CD environment.

See <<Authentication>>.

*View Command Help*

<...>

*Specify the Version Rules*

<...>  

=== Example Descriptor File

<...>

== Add the Descriptor File to Your Repositories

After you install API Catalog CLI, you must add the descriptor file, with the file name and location specified by your DevOps admin, to the repositories that you want to integrate with the publishing process.

*Prerequisites*

Before you add the descriptor file to the repository, ensure that:
API Catalog CLI is installed in your CI/CD pipeline 
For details on how to perform this installation, see <xref>. 
You have the repository location where you want to add the descriptor file ready.

To add a descriptor file to a repository:

<...>

== Publish APIs Using CLI
You can publish your APIs to Anypoint Exchange with API Catalog CLI commands. To automate the publishing of APIs using CLI, you will typically use build scripts in tools such as Jenkins, but you can run the CLI manually from a terminal for learning and testing purposes. 

=== Syntax 

<...>

=== View Command Help

<...>

=== Specify the Version Rules

<...>  



== Example API Catalog CLI Command

The following example publishes the API to the ‘4c06ba7b-3ce8-425c-878c-b728dd7db60d’ organization in the US control plane using the ./catalog.yaml descriptor file in the master branch of the VCS repository:

api-catalog-cli publishAsset -o c06ba7b-3ce8-425c-878c-b728dd7db60d  -a https://anypoint.mulesoft.com/


In the example, an assumption is made that either the username and password credentials are defined in the ANYPOINT_USERNAME and ANYPOINT_PASSWORD environment variables or that the client ID and client secret credentials are already defined.

<...>

== Example Jenkins Script 

An example Jenkins script that runs the commands is as follows:

<Example Jenkins script>

// === Authentication

// include::partial$pass-cli-credentials.adoc[]

*Authentication*

You can configure Anypoint CLI authentication with username and password, client ID and client secret, or a bearer token.
At least one method is required.

*Username and Password*

If you don't log in using single sign-on (SSO), you can use your username and password to log into the CLI directly.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `username` | Your Anypoint Platform username

You can also pass this value using the environment variable `export ANYPOINT_USERNAME=<name>`.
| `password` | Your Anypoint Platform password

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>`.
|===

For information about logging in using SSO, see xref:access-management::external-identity.adoc[About Identity Management].

*Client ID and Client Secret*

You can configure a Connected App with the `client_credentials` grant type to use with the CLI.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `client_id` | The ID of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_ID=<client_id>`.
| `client_secret` | The client secret of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_SECRET=<client_secret>`.
|===

For more information about Connected Apps, see xref:access-management::connected-apps-overview.adoc[Connected Apps].

*Bearer Token*

If you have already generated a bearer token, you can pass it to the CLI directly.
When you provide a bearer token, the CLI ignores any provided user or client credentials.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `bearer` | A bearer token for the Anypoint Platform

Your CLI session expires when the bearer token expires.
|===

For information about generating a bearer token, see https://help.mulesoft.com/s/article/How-to-generate-your-Authorization-Bearer-token-for-Anypoint-Platform[How to generate your Authorization Bearer token for Anypoint Platform].


*Reference*

The Anypoint CLI takes the following optional arguments:

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter |Description
| `organization` | Your organization within Anypoint Platform

You can also pass this value using the environment variable `export ANYPOINT_ORG=<name>`.

| `environment` | Your Anypoint Platform environment

You can also pass this value using the environment variable `export ANYPOINT_ENV=<name>`.

| `host` | The host of your Anypoint Platform Installation +
By default, this value points to `\https://anypoint.mulesoft.com`. +

* If you are using Anypoint Platform PCE, pass the address where you are hosting the platform.
* If you are using Anypoint Platform EU Cloud, pass your EU control plane URL.

You can also pass this value using a dedicated environment variable `ANYPOINT_HOST=<name>`.

|===

*Usage*

Keep the following in mind while using the Anypoint CLI:

. Environment variables override credentials file parameters and command-line parameters override environment variables. +
If you don't pass a command-line parameter, the default profile properties are used.
. If not specified, the default environment is production.
+
. Your Anypoint session expires based on the *Default session timeout* configured in your Master Organization settings.
. The Anypoint CLI works with autocomplete.
+
You can start typing the name of the command or parameter and press Tab for autocomplete or press Tab+Tab for a list of options.


*Credentials File*

The recommended way of passing these options to your Anypoint Platform CLI installation is using the `credentials` file located inside the `~/.anypoint` directory, which is not automatically created during installation. Follow these steps to create your credentials file:

. Create a directory called `.anypoint` in the `~/` directory for Linux and OSx, or `C:\Users\USERNAME \` in Windows.
. Navigate to your `.anypoint` directory and create a blank file named `credentials` with the following structure:
+
[source,text,linenums]
----
{
 "default": {
  "username": "yourAnypointUserName",
  "password": "yourAnypointPassword",
  "organization": "",
  "environment": "",
  "host": ""
 },
 "otherProfile": {
  "username": "",
  "password": "",
  "organization": "",
  "environment": "",
  "host": ""
 },
 "connAppProfile": {
  "client_id": "",
  "client_secret": "",
  "organization": "",
  "environment": "",
  "host": ""
 }
}
----
Note that the `default` profile is used unless the `ANYPOINT_PROFILE` environment variable is set:
+
[source,text,linenums]
----
> export ANYPOINT_PROFILE="otherProfile"
> anypoint-cli
----

Then run the `anypoint-cli` command without any options:

[source,text,linenums]
----
> anypoint-cli
----

*Dedicated Environment Variables*

If you choose to pass the credentials when running `anypoint-cli`, pass both parameters as environment variables: `ANYPOINT_USERNAME` and `ANYPOINT_PASSWORD`.

[source,text,linenums]
----
> export ANYPOINT_USERNAME="username"
> export ANYPOINT_PASSWORD="password"
> anypoint-cli
----

*CLI Options*

If you pass only your username, the Anypoint CLI prompts for your password.

[source,text,linenums]
----
> anypoint-cli --username="user"
Password: ****
----

*Pass Commands*

After setting up a proper way to access Anypoint Platform from the CLI, you can start passing commands. +

*Use Anypoint CLI Through a Network Proxy*

To use the Anypoint CLI through a proxy server, configure the `HTTP_PROXY` and `HTTPS_PROXY` environment variables with the hostname or IP addresses of your proxy servers.

Depending on your operating system, use the following commands:

* Linux, macOS, or Unix
+
--
`$ export HTTP_PROXY=http://__proxy-server__:80`

`$ export HTTPS_PROXY=https://__proxy-server__:443`
--

* Windows
+
--
`> set HTTP_PROXY=http://__proxy-server__:80`

`> set HTTPS_PROXY=https//__proxy-server__:443`
--

If the proxy server requires authentication, use these commands:

* Linux, macOS, or Unix
+
--
`$ export HTTP_PROXY=http://__username__:__password__@__proxy-server__:80`

`$ export HTTPS_PROXY=https://__username__:__password__@__proxy-server__:443`
--

* Windows
+
--
`> set HTTP_PROXY=http://__username__:__password__@__proxy-server__:80`

`> set HTTPS_PROXY=https://__username__:__password__@__proxy-server__:443`
--

*Notes*

* To improve the Anypoint CLI experience, we gather anonymized usage data. You can opt out by setting `collectMetrics` to false in the `credentials` file.

// Authentication end 

== See Also

* xref:anypoint-platform-cli-commands.adoc[Anypoint Platform CLI List of Commands]
Anypoint Exchange
