//Use the MultiTopic template to document subjects that include a combination of topic types. This template includes all three topic types. Remove topic types that aren’t needed, or add additional topic types when needed. 

= Publish APIs Using API Catalog CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

== API Catalog CLI

API Catalog CLI enables you to publish APIs to Anypoint Exchange as they are created and updated as part of your CI/CD processes. 

With API Catalog CLI you can:

* Publish API specifications in Exchange using CLI commands 
* Use descriptor files to explicitly define how you want the specifications to be published

For details, see the following:

* <<Install API Catalog CLI>>
* <<Create Descriptor Files>>
* <<Publish APIs Using CLI>>

== Install API Catalog CLI 

To enable developers in your organization to automatically publish the new API specifications, you must install API Catalog CLI and add it to your CI/CD pipeline. 

=== Prerequisites

* Download and install NodeJS and npm (node package manager) on your system.
+
See the https://nodejs.org/en/download/[NodeJS download page].
* Download and install the Git version management on your system.
+
See the https://git-scm.com/downloads[Git download site].

Depending on the configuration of your system, you might need to run these commands using administrator credentials.

[source,text,linenums]
----
$ npm install -g anypoint-cli@latest
----

If the installation command fails with the following error, ensure that the Git client is installed on your computer and the git protocol is not blocked by your firewall or network:

[source,text,linenums]
----
fatal: read error: Invalid argument
----

If the git protocol is blocked, you can configure Git to use `https://` instead of `git://`:

[source,text,linenums]
----
git config --global url."https://".insteadOf git://
----

System Requirements:

* Anypoint Platform account
* Anypoint Platform user account

=== Install the CLI

To install the CLI:

. Download the API Catalog CLI package from the xref:https://npmjs.com[npm public registry]. 
. Run the following command from your terminal, where <API-Catalog-CLI-package-name> is the name of the package you downloaded:
----
npm install -g <API-Catalog-CLI-package-name>@beta
----

To give access to the CLI from any directory:
----
$ npm link
$ cd ../<your-directory-name>
$ api-catalog-cli publish-asset
----

=== View Command Help* ===
<...>

== Descriptor Files

Before you run the commands to publish your APIs, you must create a descriptor file in each of the Git repositories you are using for your CI/CD processes. You can use the following approaches:

* *Dry Run Mode*: Use this mode to run the publish catalog command with an empty descriptor.yaml file and get a preview in your CI/CD log of the APIs that would be cataloged. 
* *Explicit Mode*: Use this mode to run the publish catalog command with a complete descriptor file that specifies the APIs that should be cataloged. 

=== Prerequisites

Before you add the descriptor file to the repository, ensure that:

* The API Catalog CLI is installed on a computer in your CI/CD pipeline. 
+
See <<Install the CLI>>. 
* You have the repository location where you want to add the descriptor file ready.

=== Dry Run Mode

Use dry run mode to generate content for a starter descriptor file and discover which APIs are available in a CI/CD repository that are candidates to be cataloged in Exchange. The CI/CD job sends results to standard output. The output has suggested descriptor file content and status messages, such as lists of APIs that would not be cataloged based on this descriptor content.
No API specifications or documentation are cataloged in Exchange.

To use dry run mode:

. Add an empty +descriptor.yaml+ file to your Git repository. 
. Modify your CI/CD pipeline to add the following command: 
. Run the CI/CD pipeline.
. Check your CI/CD log for the results.
. Update the +descriptor.yaml+ file in your Git repository with the content from the dry run and modify as needed. 

=== Explicit Mode

Use explicit mode when you have descriptor file content that identifies the APIs that you want to publish in Exchange. You can use dry run mode to obtain suggested content from your CI/CD repository or you can create the descriptor file by using the following documentation. 

=== Create a Descriptor File

==== api-catalog create-descriptor

----
> api-catalog create-descriptor [options] 
----

This command describes the APIs to catalog. This file is used by the api-catalog publish-asssets command to publish identified APIs to Exchange. See <<Publish APIs Using CLI>>.


[%header,cols="40a,30a,30a"]
|===
| Parameter | Description |  Default

| branches | Specifies the branches from which to pull API information to be cataloged.  |
master

| apis | A list of the APIs to be cataloged. |  N/A

| spec | The location of the specification file that describes the API. | N/A  

| asset-id | Specifies the ID of the asset to be published in Exchange. | By default this ID is generated from the API specification *Title* field.  

| docs   | A list of key and value pairs that specify the name of the documentation page and file location for the API.
These pairs define the order of the documentation pages in Anypoint Platform. +
Example: <Name of the Doc Page>:<File Location> | NULL. If not specified, no Doc pages will be imported. 

| tags  | A list of comma separated xxx text strings to describe the API. These sppear in the asset's page in Exchange. xxx  +
Example: xxx, xxx, xxx | NULL. If not specified, no tags will be added.

| categories | A list of key and value pairs that specify the category name and value. These pairs are validated against the categories that exist in the Anypoint Platform organization. +
Example: <Category Name>: <Value(s)> | NULL. If not specified, no categories will be added.

| custom-fields| A list of key and value pairs that specify the field and value. These pairs are validated against the custom fields and field types that exist in the Anypoint Platform organization. +
Example: <Field>: <Value> | NULL. If not specified, no categories will be added.

|===

Although you can enter authentication credentials explicitly in the commands for testing purposes, you should use secure authentication in your CI/CD environment.

See <<Authentication>>.

*Specify the Version Rules*

<...>  

=== Example Descriptor File

<...>

== Add the Descriptor File to Your Repositories

After you install API Catalog CLI, you must add the descriptor file, with the file name and location specified by your DevOps admin, to the repositories that you want to integrate with the publishing process.

*Prerequisites*

Before you add the descriptor file to the repository, ensure that:
API Catalog CLI is installed in your CI/CD pipeline 
For details on how to perform this installation, see <xref>. 
You have the repository location where you want to add the descriptor file ready.

To add a descriptor file to a repository:

<...>

== Publish APIs Using CLI
You can publish your APIs to Anypoint Exchange with API Catalog CLI commands. To automate the publishing of APIs using CLI, you will typically use build scripts in tools such as Jenkins, but you can run the CLI manually from a terminal for learning and testing purposes. 

// copied from Anypoint CLI for formatting help

=== api-catalog publish-asset

----
> api-catalog publish-asset [options] 
----

This command publishes APIs to Exchange using the descriptor information passed in the YAML file passed in the catalog-file option.


[%header,cols="40a,30a,30a"]
|===
| Parameter | Description |  Example

| -a, --anypoint-uri=anypoint-uri  | (required) [default: https://anypoint.mulesoft.com] The Anypoint Platform Base URL.  |
For the US Anypoint Platform, this will be 
'https://anypoint.mulesoft.com/'. Alternatively you can define this in the ANYPOINT_BASE_URL environment variable.

| -d, --dry-run=dry-run  | Indicates that the command should be run to identify the APIs that are eligible to be published, but no APIs will be published. The descriptor file will define the scope. |   

| -t, --trigger=branch:master --trigger=tag:bla  | Filters that will be applied to the descriptor file in order to decide if an asset should be published or not. |     

|  -c, --catalog-file=catalog-file  | [default: ./catalog.yaml] The name and location of the catalog descriptor file. Alternatively you can define this in the ANYPOINT_CATALOG_FILE environment variable. |     

| -o, --organization=organization   | (required) The ID of the Anypoint Organization where the APIs will be cataloged. Alternatively you can define this in the ANYPOINT_TARGET_ORGANIZATION environment variable. | 

| -p, --password  | Prompt Anypoint password for username. To avoid the need for a prompt, you can define this in the ANYPOINT_PASSWORD environment variable. |

| -u, --username=username | Anypoint username. Alternatively you can define this in the ANYPOINT_USERNAME environment variable. | 

| -v, --verbose | Turn on verbose logging. |

| -s, --silent | Turn on silent logging.|

| -r, --result  | Turn on result mode. |

| --client-id=client-id | Connected App client id. Alternatively you can define this in the ANYPOINT_CLIENT_ID environment variable. |

| --client-secret  | Prompt Connected App secret for clientId. To avoid the need for a prompt, you can define this in the ANYPOINT_CLIENT_SECRET environment variable. |


|===


// end of copied section 

=== View Command Help

<...>

=== Specify the Version Rules

<...>  

For information on passing credentials, see <<Authentication>>.

== Example API Catalog CLI Command

The following example publishes the API to the ‘4c06ba7b-3ce8-425c-878c-b728dd7db60d’ organization in the US control plane using the ./catalog.yaml descriptor file in the master branch of the VCS repository:

api-catalog-cli publishAsset -o c06ba7b-3ce8-425c-878c-b728dd7db60d  -a https://anypoint.mulesoft.com/


In the example, an assumption is made that either the username and password credentials are defined in the ANYPOINT_USERNAME and ANYPOINT_PASSWORD environment variables or that the client ID and client secret credentials are already defined.

<...>

// Triggering and Filtering Text

Triggering and Filtering conditions work as part of publishing from the CLI (--trigger parameter). This gives you full control over when you want to publish as part of your CI/CD pipeline.

// More info can be found here:
// https://docs.google.com/document/d/1j31ANa7hQpJ9X2PCLDxZXUrFK42qPjng9jGstNBBSX4/edit

// end of Triggering and Filtering text

// Force Publish Text

If the same version of an API exists and you want to overlay it, you will need to use the force publish command.

//publish errors/skip cases for our clients to be able to solve them.
//For example, understanding the case in which the CLI skips the publication since the API content is exactly the same as the latest published version in Exchange. We may also want to document the "force-publish" parameter to be able to bypass this CLI restriction in case clients still want to publish a new identical version.//

// end Force Publish Text

== Example Jenkins Script 

An example Jenkins script that runs the commands is as follows:

<Example Jenkins script>

== Authentication

You can configure Anypoint CLI authentication with username and password, client ID and client secret, or a bearer token.
At least one method is required.

=== Username and Password

If you don't log in using single sign-on (SSO), you can use your username and password to log into the CLI directly.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `username` | Your Anypoint Platform username

You can also pass this value using the environment variable `export ANYPOINT_USERNAME=<name>`.
| `password` | Your Anypoint Platform password

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>`.
|===

For information about logging in using SSO, see xref:access-management::external-identity.adoc[About Identity Management].

=== Client ID and Client Secret

You can configure a Connected App with the `client_credentials` grant type to use with the CLI.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `client_id` | The ID of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_ID=<client_id>`.
| `client_secret` | The client secret of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_SECRET=<client_secret>`.
|===

For more information about Connected Apps, see xref:access-management::connected-apps-overview.adoc[Connected Apps].

=== Reference

API Catalog CLI takes the following optional arguments:

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter |Description
| `organization` | Your organization within Anypoint Platform

You can also pass this value using the environment variable `export ANYPOINT_ORG=<name>`.

| `environment` | Your Anypoint Platform environment

You can also pass this value using the environment variable `export ANYPOINT_ENV=<name>`.

| `host` | The host of your Anypoint Platform Installation +
By default, this value points to `\https://anypoint.mulesoft.com`. +

* If you are using Anypoint Platform PCE, pass the address where you are hosting the platform.
* If you are using Anypoint Platform EU Cloud, pass your EU control plane URL.

You can also pass this value using a dedicated environment variable `ANYPOINT_HOST=<name>`.

|===

=== Usage

Keep the following in mind while using API Catalog CLI:

. Command-line parameters override environment variables. +
If you don't pass a command-line parameter, the default profile properties are used.
. If not specified, the default environment is production.
+
. Your Anypoint session expires based on the *Default session timeout* configured in your Master Organization settings.

// Authentication end 

== See Also

* xref:anypoint-platform-cli-commands.adoc[Anypoint Platform CLI List of Commands]
Anypoint Exchange
