= Publish APIs Using API Catalog CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

== Get Started With API Catalog CLI

API Catalog CLI enables you to publish APIs to Anypoint Exchange as they are created and updated as part of your CI/CD processes. 

With API Catalog CLI you can:

* Publish API specifications in Exchange using CLI commands 
* Use descriptor files to identify the APIs to publish 

You should install and test the process end-to-end locally before integrating it into your CI/CD pipeline. To verify locally: 

. <<Install API Catalog CLI,Install>> the API Catalog CLI.
. Ensure MuleSoft has enabled the API Catalog entitlement for your Anypoint Platform organization.
. <<Configure Catalog Permissions in Anypoint Access Management, Configure>> required catalog permissions.
. <<Create a Descriptor File>> using the API Catalog CLI.
. <<Publish APIs Using CLI,Catalog a test asset>> using the API Catalog CLI and view it in Anypoint Exchange.

After you have finished testing locally, you will be ready to add the `api-catalog publish-asset` command to your CI/CD scripts and autocatalog APIs as part of your CI/CD processes. 

== Install API Catalog CLI 

To enable developers in your organization to automatically publish the new API specifications, you must install API Catalog CLI and add it to your CI/CD pipeline. 

=== Prerequisites

* Download and install NodeJS and npm (node package manager) on your system. See the https://nodejs.org/en/download/[NodeJS download page^].

=== Install the CLI

To install the CLI:

. Download the API Catalog CLI package from the https://npmjs.com[npm public registry^]. 
. Run the following command from your terminal:
----
npm install -g api-catalog-cli@beta
----

=== View Command Help

Use the help argument with the commands to list the commands or command options and their descriptions:

* `api-catalog --help`
* `api-catalog autocomplete --help`
* `api-catalog create-descriptor --help`
* `api-catalog publish-asset --help`

NOTE: Optionally use the `api-catalog autocomplete` command by following the instructions in the command help. 

== Configure Catalog Permissions in Anypoint Access Management

You must enable the API Catalog Contributor permission for the Anypoint Platform organization user. 

*Prerequisites*

* The API Catalog entitlement must be set by MuleSoft for your Anypoint Platform organization. 

NOTE: Permissions must be set by an Anypoint Platform user with administrative permission. 

To enable the API Catalog Contributor permission:

. In Anypoint Platform, navigate to *Access Management*.
. Select *Users*.
. Select the user for which you want to enable the permission. 
. In the *Permissions* tab, select the *API Catalog* subtab.
. Select *API Catalog Contributor*. 

== Create a Descriptor File

Before you run the commands to publish your APIs, you must create a descriptor file that has the information Exchange needs to catalog the APIs. Use the following command to autodiscover APIs and generate the descriptor information. 

==== api-catalog create-descriptor

----
> api-catalog create-descriptor [options] 
----

*Options*

`-f, --file=file`
  +
  [default: `catalog.yaml`] 
  + 
  The name and location in which to save the generated catalog descriptor file.

The result of the command depends on the presence and content of the designated descriptor file as follows:

* No file or empty file: The command will discover the APIs and write the results to standard output and to a file named `catalog.yaml`.

* Existing file with content: The command will fail and show an error message that says the descriptor file already exists.

//Limitations:
//* Each API specification must have a single API.  
//* You cannot log in through the CLI if you system uses multi-factor authentication. Your system must use SSO and you must log in using the client ID and client secret of the Connected App.

=== Create a Descriptor File Using the CLI

You can run the `api-catalog create-descriptor` command to create and print the catalog descriptor YAML results to a designated file. The command will output cataloging information for all API specifications it finds in the full directory tree relative to the current working directory.

To create a descriptor file:

. Navigate to the directory path that contains the APIs you want to catalog. 
. Run the `api-catalog create-descriptor` command. For example:
+
----
> api-catalog create-descriptor -f mydescriptor.yaml
----

NOTE: You can optionally create a descriptor file manually instead of using the `api-catalog create-descriptor` command to generate the file. See <<Create a Descriptor File Manually>>.


== Publish APIs Using CLI

You can publish your APIs to Anypoint Exchange with API Catalog CLI commands. To automate the publishing of APIs using CLI, you will typically use build scripts in tools such as Jenkins, but you can run the CLI manually from a terminal for learning and testing purposes. 

*Prerequisites*

* Create a descriptor file and copy it to the file path where your API projects are stored. See <<Create a Descriptor File>>.

=== api-catalog publish-asset

----
> api-catalog publish-asset [options] 
----

This command publishes APIs to Exchange using the YAML descriptor information specified in the `--descriptor-file` option.

[%header,cols="20a,80a"]
|===
| Option | Description 

| -a, --anypoint-uri=anypoint-uri 

or

ANYPOINT_BASE_URL environment variable

 | (Required) 

Default: https://anypoint.mulesoft.com

The Anypoint Platform base 
URL. It must be specified using HTTPS protocol. 

For the US Anypoint Platform, use  
`https://anypoint.mulesoft.com/`. 

For the European Anypoint Platform, use  
`https://eu1.anypoint.mulesoft.com/`. 


|  -d, --descriptor-file=descriptor-file 

or

ANYPOINT_DESCRIPTOR_FILE environment variable

 | Default:  ./catalog.yaml 
 
The name and location of the catalog descriptor file.  

  * If the file does not exist, no assets will be cataloged.
  * If the file exists but is empty, the command will create and print the catalog descriptor YAML results. It will output cataloging information for all API specifications it finds in the full directory tree relative to the current working directory.
  * If a valid YAML file exists, the command will catalog the assets as specified. 
  
See <<Create a Descriptor File>>. 

| --dry-run | Runs the command to verify that the descriptor file is valid. No APIs will be published. 

| -o, --organization=organization 

or

ANYPOINT_TARGET_ORGANIZATION environment variable

  | (Required) 
  
The ID of the Anypoint Organization where the APIs will be cataloged.  

| -p, --password 

or

ANYPOINT_PASSWORD environment variable

 | Anypoint user password. Set the environment variable to avoid a prompt for the password.  
 
See <<Authentication>>. 

| -s, --silent | Enable silent logging.

| -t, --trigger=<descriptor-tag>:<value> --trigger=<descriptor-tag>:value  | Conditions that are applied to the descriptor file to determine whether an asset should be published. To set multiple conditions, specify separate --trigger options for each condition.

Example:

---

 --trigger=branch:main --trigger=tag:hotfix -- trigger=user:admin

---

The `--trigger` options work in conjunction with the `triggerConditions` section in the descriptor file. See <<Descriptor YAML Schema>>  

| -u, --username=username 

or

ANYPOINT_USERNAME environment variable

| Anypoint username. 

See <<Authentication>>. 

| -v, --verbose | Enable verbose logging. 



| --async |  Run the publish job asynchronously. 

| --client-id=client-id 

or

ANYPOINT_CLIENT_ID environment variable

| Connected app client ID.  

See <<Authentication>>.

| --client-secret 

or

ANYPOINT_CLIENT_SECRET environment variable

 | Prompt for the Connected App secret for the client ID. Set the environment variable to avoid the prompt for the client secret.  
 
See <<Authentication>>.
 
 | --force-publish |  Bypasses the comparison and 
 creates a new version of the asset in Exchange regardless of the content.

| --force-update-metadata | Updates the asset's metadata (such as tags) in the latest version in Exchange regardless of the content. This does not republish the asset. 

| --json | Prints the execution result in JSON format. 

|===

=== Example Publish Asset Commands

Following are examples that show some typical use cases for publishing assets.

==== Example 1: Publish an asset with default settings

The following example publishes the API to an organization in the US Anypoint Platform control plane. Defaults or environment variable settings will be used for the unspecified options. 

---
 api-catalog-cli publishAsset -o 1234abc-b34a-7cd3-4s32-12345abc2345  -a https://anypoint.mulesoft.com/

---

In the example, an assumption is made that either the username and password credentials are defined in the ANYPOINT_USERNAME and ANYPOINT_PASSWORD environment variables or that the client ID and client secret credentials are already defined in ANYPOINT_CLIENT_ID and ANYPOINT_CLIENT_SECRET environment variables. 

==== Example 2: Do a dry run to ensure the descriptor file is valid

This example shows the `api-catalog publish-asset` command with the following options:

* --dry-run: Runs the command to verify that the descriptor file is valid but doesn't publish the APIs
* --verbose: Shows the maximum information in the results

It sends the standard output to `mycatdryrun.log`. 

--- 
 api-catalog publish-asset -a https://anypoint.mulesoft.com -d catalog.yaml -o 1234abc-b34a-7cd3-4s32-12345abc2345 --client-id=1234567abcd2345gabc987656abc --client-secret --dry-run --verbose >> mycatdryrun.log

---

==== Example 3: Publish an asset regardless of the content

If you want to publish a new version of the asset in Exchange regardless of the content, you should use the `--force-publish` option. 

This example shows the `api-catalog publish-asset` command with both of these options. This example assumes that authentication credentials are set in environment variables.

----
> api-catalog publish-asset -a https://anypoint.mulesoft.com --descriptor-file=mydescriptor.yaml -o 1234abc-b34a-7cd3-4s32-12345abc2345 --force-publish 

----

==== Example 4: Publish an asset using trigger conditions 

Custom trigger conditions enable you to further control what is published when the API Catalog CLI command runs. 

This example shows `api-catalog publish-asset` command options that will publish only the APIs that are identified in the `triggerConditions` section of a descriptor file called `mydescriptor.yaml`.  

*Command to publish:*

----
> api-catalog publish-asset -a https://anypoint.mulesoft.com -d mydescriptor.yaml -o 1234abc-b34a-7cd3-4s32-12345abc2345 -u myAnyPtAccount -p myPwd@4!myacct --trigger=ref:main --trigger=tag:migrate --trigger=status:complete

----

*Section in the specified descriptor file:*

---
 
 triggerConditions:
  ref:
   - main
  tags:
   - migrate
   - republish
  status:
   - complete
   - ready

---

==== Example 5: Publish Using a Jenkins Script 

This example shows a Jenkins script that runs the `api-catalog publish-asset` command.

---

 pipeline {
    agent any
    environment {
        ANYPOINT_ORG_ID = '1234abc-b34a-7cd3-4s32-12345abc2345'
        CATALOG_DESCRIPTOR = './descriptor.yaml'
     }   
     stages {
        stage('git checkout') {
            steps {
                git url: 'git@github.com:mulesoft-labs/api-cataloging-demo.git'
                sh 'ls'
                echo "Branch " + env.GIT_BRANCH
            }
        }
        stage('Build Artifacts') {    
            steps {
                 // building
                  sh 'ls'
            }
        }
        stage('API Cataloging') {    
            steps {
                 withCredentials([
                    usernamePassword(credentialsId: 'anypoint-demo-org-creds',
                    usernameVariable: 'ANYPOINT_USERNAME',
                    passwordVariable: 'ANYPOINT_PASSWORD')
                ]) { 
                    sh 'api-catalog-cli publish-asset -d $CATALOG_DESCRIPTOR -o $ANYPOINT_ORG_ID -a https://anypoint.mulesoft.com/ --trigger=branch:main'
                }
            }
        }
         stage('Deploy') {    
            steps {
                // Lots of deploying 
                 echo "Branch " + env.GIT_BRANCH
                 sh 'ls'
            }
        }
    }

---

== Authentication

You can configure Anypoint CLI authentication with username and password, client ID and client secret, or a bearer token.
At least one method is required.

=== Username and Password

If you don't log in using single sign-on (SSO), you can use your username and password to log into the CLI directly.

[%header%autowidth.spread,cols="a,a"]
|===
| Argument | Description
| `username` | Your Anypoint Platform username

You can also pass this value using the environment variable `export ANYPOINT_USERNAME=<name>`.
| `password` | Your Anypoint Platform password

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>`.
|===

For information about logging in using SSO, see xref:access-management::external-identity.adoc[About Identity Management].

=== Client ID and Client Secret

You can configure a Connected App with the `client_credentials` grant type to use with the CLI.

[%header%autowidth.spread,cols="a,a"]
|===
| Argument | Description
| `client_id` | The ID of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_ID=<client_id>`.
| `client_secret` | The client secret of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_SECRET=<client_secret>`.
|===

For more information about Connected Apps, see xref:access-management::connected-apps-overview.adoc[Connected Apps].

=== Environment Variable Usage

Keep the following in mind while using API Catalog CLI:

* Command-line options override environment variables. +
If you don't pass a command-line Argument, the default profile properties are used.
* If not specified, the default environment is production.

=== Timeout

Your Anypoint session expires based on the *Default session timeout* configured in your Organization settings.

// Authentication end 

== Create a Descriptor File Manually

You can optionally create a descriptor file manually rather than using the `api-catalog create-descriptor` command to create it. 

After you create the descriptor file, copy it to the file path or repository where your API projects are stored. 

The descriptor file must start with the following:

---

 #%Catalog Descriptor 0.6

---

TIP: Run the `api-catalog publish-asset` command using the `--dry-run` option to ensure your manually-created descriptor file is valid. 

=== Descriptor YAML Schema

Following are the YAML tags used to describe the APIs you want to catalog. 

[%header,cols="20a,80a"]
|===
| Tag | Description 

| triggerConditions | This section enables you to set conditions to restrict the APIs that are included when the `api-catalog publish-asset` command is run.   

This example sets `triggerConditions` to enable the `api-catalog publish-asset` command to set conditions to publish APIs for just a designated branch or reference, tagged in a certain way, and authored by a specific user. 

---
 branches:
   - main
   - release/(.*)
 tags:
   - support
   - release/(.*)
 user:
   - admin

---

| contact | The contact name and email ID.   

| apis | A list of the APIs to be cataloged. 

spec:: The location of the specification file that describes the API. 

assetId:: Specifies the ID of the asset to be published in Exchange. 

docs:: A list of key and value pairs that specify the name of the documentation page and file location for the API.
These pairs define the order of the documentation pages in Anypoint Platform.
+
Format: <Name of the documentation page>:<File Location>
+
If this option is not specified, no documentation pages will be imported. 

categories:: A list of key and value pairs that specify the category name and value. These pairs are validated against the categories that exist in the Anypoint Platform organization.
+
Format: <Category Name>: <Value(s)>
+
If this option is not specified, no categories will be added.

customFields:: A list of key and value pairs that specify the field and value. These pairs are validated against the custom fields and field types that exist in the Anypoint Platform organization.
+
Format: <Field>: <Value(s)> 
+
If this option is not specified, no custom fields will be added.

versioning:: The asset version. 
+
If this is not specified, the patch version is incremented by one.
+
Example: ~1.x.x  
+
See <<Asset Versioning>>.

apiVersion:: The API version for the asset. 
+
If the API version is not specified in the descriptor file, the version from the specification file is used. If the API version is specified in both files, the value in the descriptor file is used. The value must be specified in one of the files. 
+
Example: v1  

|===

=== Asset Versioning

When you publish a version of an asset that already exists in Exchange, the patch version is incremented by default. However, you can set the version using semantic versioning notation `x.x.x` for major, minor, and patch versions respectively. 

Use the following symbols before the version nodes to control how an asset version is incremented:

* ^ patch

* ~ minor

* & major  +
 Because '&' is a reserved character in YAML, a semantic versioning string using this character must be enclosed in a single quote. For example: '&x.x.x'

==== Examples of Asset Versioning

The following table shows how the asset version is incremented for example semantic versioning strings. 

[%header,cols="15a, 70a"]
|===
| Asset Version (versioning) 

| Explanation

| ^x.x.x (Default) | Search for the latest version and increment the patch

| ^1.x.x | Search for the latest version of major 1 and increment the patch

| ~1.x.x| Search for the latest version of major 1 and increment the minor

| ^1.0.x | Search for the latest version of major 1, minor 0 and increment the patch

| ^3.x.x | Search for the latest version of major 3 and increment the patch

| ^3.x.x | Search for the latest version of major 3 and increment the patch

| '&x.x.x' | Increment to the next the major version. 

|===

For more information on asset versioning in Exchange, see xref:to-change-raml-version.adoc[Change the Version of an API Asset].

=== Example Descriptor File

Following is an example descriptor file that describes the cataloging information for two APIs. 

[source,yaml]
---
 #%Catalog Descriptor 0.6 # <1>
 triggerConditions: # <2>
  branches:
    - main
    - release/(.*)
  tags:
    - support
    - release/(.*)
  user:
    - admin
 contact: # <3>
  name: 'John Doe'
  email: 'john.doe@org.com'
 apis: # <4>
  - spec: api-spec/codat.json
    assetId: codat-api
    docs:
      add: api-spec/add.md
      home: home.md
    customFields:
      custom: value
      another: field
    tags:
      - codat
      - gcp
    versioning: 2.0.x
    apiVersion: v3
  - spec: api-spec/billing-api.json
    assetId: my-awesome-api
    tags:
      - finance
      - aws
    categories:
      API Type:
        - System API
        - Experience API
      Organization:
        - Finance
        - Billing
    versioning: ~1.x.x
    apiVersion: v1
---
<1> Provides the start line for the descriptor file
<2> Sets trigger conditions
<3> Provides the contact name and email ID 
<4> Specifies the API information to be published

== See Also

* xref:anypoint-platform-cli-commands.adoc[Anypoint Platform CLI List of Commands]