= Publish APIs Using API Catalog CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

API Catalog CLI enables you to catalog your API specifications, documentation files, and associated metadata as part of an automated process. You can embed the command to publish assets in your automation tools, such as a CI/CD pipeline or custom scripts, to automatically trigger the cataloging of your API assets. API Catalog CLI is agnostic of CI/CD tools and runtime environments.

== Get Started with API Catalog CLI

To get started with API Catalog CLI: 

. Ensure MuleSoft has enabled the API Catalog entitlement for your Anypoint Platform organization.
. <<Install API Catalog CLI,Install>> the API Catalog CLI.
. <<Configure Catalog Permissions in Anypoint Access Management, Configure>> required catalog permissions.
. <<Create a Descriptor File Using the CLI,Create a descriptor file>> to identify the APIs to publish.
. <<Publish APIs Using the CLI,Catalog an asset>> using the API Catalog CLI and view it in Anypoint Exchange.

TIP: Consider testing the process end-to-end locally before integrating it into your CI/CD pipeline or custom scripts. 

== Install API Catalog CLI 

To enable developers in your organization to automatically publish the new API specifications, you must install API Catalog CLI. 

=== Prerequisites

* Download and install the latest LTS version of NodeJS and npm (node package manager) on your system. See the https://nodejs.org/en/download/[NodeJS download page^]. 

=== Install the CLI

To install the CLI:

. Download the API Catalog CLI package from the https://npmjs.com[npm public registry^]. 
. Run the following command from your terminal:
----
npm install -g api-catalog-cli@beta
----

NOTE: The install command might give warning messages about the version of npm because the API Catalog CLI installation package is built using npm version 14. You can ignore these messages. 

=== View Command Help

Use the help option with the commands to list the commands or command options and their descriptions. The following examples show how the help option is used with each of the commands:

----
api-catalog --help
api-catalog autocomplete --help
api-catalog create-descriptor --help
api-catalog publish-asset --help
----

NOTE: You can optionally configure the `api-catalog autocomplete` command so that you can use the tab key with a partially typed command to autocomplete it. See <<Configure Command Autocompletion>> for more details.

== Configure Catalog Permissions in Anypoint Access Management

You must enable the API Catalog Contributor permission for the Anypoint Platform organization user. 

=== Prerequisites

* The API Catalog entitlement must be set by MuleSoft for your Anypoint Platform organization. 

NOTE: Permissions must be set by an Anypoint Platform user with administrative permission. 

To enable the API Catalog Contributor permission:

. In Anypoint Platform, navigate to *Access Management*.
. If you are managing user access using teams, click `Hide New Features`.
. Select *Users*.
. Select the user for which you want to enable the permission.  
. Select the *API Catalog Contributor* permission. 
. If you hid new features in a preceding step, to continue managing user access using teams, click `Try New Features`.

== Create a Descriptor File Using the CLI

Before you run the commands to publish your APIs, you must create a descriptor file that has the information Exchange needs to catalog the APIs. You can create the descriptor file using the CLI or you can create it manually. Typically you should create the file using the CLI and if you need to set more options to control how the assets are published, you can update the file manually. 

You can run the `api-catalog create-descriptor` command to create and print the catalog descriptor YAML results to a designated file. The command will output cataloging information for all API specifications it finds in the full directory tree relative to the current working directory.

To create a descriptor file using the CLI:

. Navigate to the directory path that contains the APIs you want to catalog. 
. Run the `api-catalog create-descriptor` command. The following example creates a descriptor file called `mydescriptor.yaml` in the current path:
+
----
> api-catalog create-descriptor -f mydescriptor.yaml
----

The result of the command depends on the presence and content of the designated descriptor file as follows:

* No file or empty file: The command will discover the APIs and write the results to standard output and to a file named `catalog.yaml`.

* Existing file with content: The command will fail and show an error message that says the descriptor file already exists.

NOTE: You can alternatively create a descriptor file manually instead of using the `api-catalog create-descriptor` command to generate the file. See <<Create or Update a Descriptor File Manually>>.

==== api-catalog create-descriptor

Following is a reference for the `api-catalog create-descriptor` command. 

*Usage*

----
> api-catalog create-descriptor [options] 
----

*Options*

`-f, --file=file`
  +
  [default: `catalog.yaml`] 
  + 
  The name and location in which to save the generated catalog descriptor file.

== Publish APIs Using the CLI

You can use the `api-catalog publish-asset` command to publish your APIs to Exchange. You will typically embed this command in your automation tools, such as a CI/CD pipeline or custom scripts, to automatically trigger the cataloging of your API assets. The command publishes your APIs using the information in the file specified in the `--descriptor-file` option.   

=== Prerequisites

Create a descriptor file that describes the APIs to publish and copy it to the file path where your API projects are stored. See <<Create a Descriptor File Using the CLI>>.

=== Limitations

This version of API Catalog CLI has the following limitations:

* Documentation must be in Markdown format.
* Images in documentation are resolved only if the references are full URLs that point to externally hosted images. 
* External resources in documentation are resolved only if the references are full URLs that point to externally hosted resources.
* The main documentation page must be called `home.md`.

To publish an API using the CLI:

* Run the `api-catalog publish-asset` command. The following example publishes APIs described in the `catalog.yaml` file:
+
----
> api-catalog publish-asset -a https://anypoint.mulesoft.com -d catalog.yaml -o 1234abc-b34a-7cd3-4s32-12345abc2345 -u myAnyPtAccount -p myPwd@4!myacct 
----

=== api-catalog publish-asset

Following is a reference for the `api-catalog publish asset` command. 

*Usage*

----
> api-catalog publish-asset [options] 
----

*Options*

The `api-catalog publish-asset` options are described in the following table.

[%header,cols="20a,80a"]
|===
| Option | Description 

| -a, --anypoint-uri=anypoint-uri 

or

ANYPOINT_BASE_URL environment variable

 | (Required) 

Default: `https://anypoint.mulesoft.com`

The Anypoint Platform base 
URL. It must be specified using HTTPS protocol. 

For the US Anypoint Platform, use:  
`https://anypoint.mulesoft.com/`. 

For the European Anypoint Platform, use: 
`https://eu1.anypoint.mulesoft.com/`. 


|  -d, --descriptor-file=descriptor-file 

or

ANYPOINT_DESCRIPTOR_FILE environment variable

 | Default:  ./catalog.yaml 
 
The name and location of the catalog descriptor file.  

  * If the file does not exist, no assets will be cataloged.
  * If the file exists but is empty, the command will create and print the catalog descriptor YAML results. It will output cataloging information for all API specifications it finds in the full directory tree relative to the current working directory.
  * If a valid YAML file exists, the command will catalog the assets as specified. 
  
See <<Create a Descriptor File Using the CLI>>. 

| --dry-run | Runs the command to verify that the descriptor file is valid. No APIs are published. 

| -o, --organization=organization 

or

ANYPOINT_TARGET_ORGANIZATION environment variable

  | (Required) 
  
The ID of the Anypoint Organization where the APIs will be cataloged.  

| -p, --password 

or

ANYPOINT_PASSWORD environment variable

 | Anypoint user password. Set the environment variable to avoid a prompt for the password.  
 
See <<Authentication>>. 

| -s, --silent | Enable silent logging.

| -t, --trigger=<descriptor-tag>:<value> --trigger=<descriptor-tag>:value  | This option works in conjunction with the custom `triggerConditions` section in the descriptor file. For each run of the `api-catalog publish-asset` command, the trigger values are compared to trigger condition values in the descriptor file to determine whether to publish the APIs described in the descriptor file. To match multiple conditions, specify separate `--trigger` options for each condition. For the APIs to be published, all trigger conditions set in the descriptor file must be matched by `--trigger` option values.

Example:

---

 --trigger=branch:main --trigger=anytag:release/ -- trigger=user:admin

---

See <<Descriptor YAML Schema>>. 

| -u, --username=username 

or

ANYPOINT_USERNAME environment variable

| Anypoint username. 

See <<Authentication>>. 

| -v, --verbose | Enable verbose logging. 



| --async |  Run the publish job asynchronously. 

| --client-id=client-id 

or

ANYPOINT_CLIENT_ID environment variable

| Connected app client ID.  

See <<Authentication>>.

| --client-secret 

or

ANYPOINT_CLIENT_SECRET environment variable

 | Prompt for the Connected App secret for the client ID. Set the environment variable to avoid the prompt for the client secret.  
 
See <<Authentication>>.
 
 | --force-publish |  Bypasses the comparison and 
 creates a new version of the asset in Exchange regardless of the content.

| --force-update-metadata | Updates the asset's metadata, such as tags, in the latest version in Exchange regardless of the content. This does not republish the asset. 

| --json | Prints the execution result in JSON format. 

|===

The following sections give example commands that show how several catalog options are used:

* <<Publish an Asset with Default Settings>>

* <<Perform a Dry Run to Validate the Descriptor File>>

* <<Publish an Asset Regardless of the Content>>

* <<Publish an Asset Using Trigger Conditions>>

* <<Publish Using a Jenkins Script>> 

=== Publish an Asset with Default Settings

The following example publishes the API to an organization in the US Anypoint Platform control plane. Defaults or environment variable settings are used for the unspecified options. 

----
> api-catalog-cli publishAsset -o 1234abc-b34a-7cd3-4s32-12345abc2345  -a https://anypoint.mulesoft.com/

----

This example assumes that either the username and password credentials are defined in the ANYPOINT_USERNAME and ANYPOINT_PASSWORD environment variables or that the client ID and client secret credentials are already defined in ANYPOINT_CLIENT_ID and ANYPOINT_CLIENT_SECRET environment variables. 

=== Perform a Dry Run to Validate the Descriptor File

This example shows the `api-catalog publish-asset` command with the following options:

* --dry-run: Runs the command to verify that the descriptor file is valid but doesn't publish the APIs
* --verbose: Shows the maximum information in the results

The example command sends the standard output to `mycatdryrun.log`. 

----
> api-catalog publish-asset -a https://anypoint.mulesoft.com -d catalog.yaml -o 1234abc-b34a-7cd3-4s32-12345abc2345 --client-id=1234567abcd2345gabc987656abc --client-secret --dry-run --verbose >> mycatdryrun.log

----

=== Publish an Asset Regardless of the Content

To publish a new version of the asset in Exchange regardless of the content, use the `--force-publish` option. 

This example shows the `api-catalog publish-asset` command with both of these options. This example assumes that authentication credentials are set in environment variables.

----
> api-catalog publish-asset -a https://anypoint.mulesoft.com --descriptor-file=mydescriptor.yaml -o 1234abc-b34a-7cd3-4s32-12345abc2345 --force-publish 

----

=== Trigger the Publish Using Conditions 

Custom trigger conditions enable you to control whether APIs are published when the API Catalog CLI command runs. This example shows how `--trigger` options correlate with descriptor file trigger conditions to control whether or not to publish the described APIs.   

*Example Trigger Conditions in a Descriptor file*

Following is an example `triggerConditions` section in the `mydescriptor.yaml` descriptor file:

---
 
 triggerConditions:
  ref:
   - main
  tags:
   - migrate
   - republish
  status:
   - complete
   - ready

---

*Example That Triggers the Publish*

The following command triggers the API publish because the trigger option values match all of the trigger conditions in the `mydescriptor.yaml` descriptor file. 

----
> api-catalog publish-asset -a https://anypoint.mulesoft.com -d mydescriptor.yaml -o 1234abc-b34a-7cd3-4s32-12345abc2345 -u myAnyPtAccount -p myPwd@4!myacct --trigger=ref:main --trigger=tags:migrate --trigger=status:complete

----

*Example That Does Not Trigger the Publish*

The following command does not trigger the API publish because the trigger option value for `ref` is `test`, not `main`. Because not all trigger values match the corresponding trigger conditions, no APIs are published. 

----
> api-catalog publish-asset -a https://anypoint.mulesoft.com -d mydescriptor.yaml -o 1234abc-b34a-7cd3-4s32-12345abc2345 -u myAnyPtAccount -p myPwd@4!myacct --trigger=ref:test --trigger=tags:migrate --trigger=status:complete

----

=== Publish Using a Jenkins Script 

This example shows a Jenkins script that runs the `api-catalog publish-asset` command.

[source,java]
----
pipeline {
    agent any
    environment {
        ANYPOINT_ORG_ID = '1234abc-b34a-7cd3-4s32-12345abc2345'
        CATALOG_DESCRIPTOR = './descriptor.yaml' <1>
     }   
     stages {
        stage('git checkout') {
            steps {
                git url: 'git@github.com:mygitlocation/api-catalog-cli.git'
                // additional checkout tasks
            }
        }
        stage('Build Artifacts') {    
            steps {
                 // building
            }
        }
        stage('API Cataloging') {    
            steps {
                 withCredentials([
                    usernamePassword(credentialsId: 'my-anypoint-creds',
                    usernameVariable: 'ANYPOINT_USERNAME',
                    passwordVariable: 'ANYPOINT_PASSWORD')
                ]) { 
                    sh 'api-catalog-cli publish-asset -d $CATALOG_DESCRIPTOR -o $ANYPOINT_ORG_ID -a https://anypoint.mulesoft.com/ --trigger=branch:main' <2>
                }
            }
        }
         stage('Deploy') {    
            steps {
                // Any deployment tasks to be performed, here.
            }
        }
    }
----
<1> Defines the organization and descriptor file values
<2> Runs the `api-catalog publish-asset` command to publish APIs found in the `main` Github branch

== Authentication

You can configure Anypoint CLI authentication with username and password, client ID and client secret, or a bearer token.
At least one method is required.

=== Username and Password

If you don't log in using single sign-on (SSO), you can use your username and password to log in to the CLI directly.

[%header%autowidth.spread,cols="a,a"]
|===
| Argument | Description
| `username` | Your Anypoint Platform username

You can also pass this value using the environment variable `export ANYPOINT_USERNAME=<name>`.
| `password` | Your Anypoint Platform password

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>`.
|===

For information about logging in using SSO, see xref:access-management::external-identity.adoc[About Identity Management].

=== Client ID and Client Secret

You can configure a Connected App with the `client_credentials` grant type to use with the CLI.

[%header%autowidth.spread,cols="a,a"]
|===
| Argument | Description
| `client_id` | The ID of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_ID=<client_id>`.
| `client_secret` | The client secret of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_SECRET=<client_secret>`.
|===

For more information about Connected Apps, see xref:access-management::connected-apps-overview.adoc[Connected Apps].

=== Environment Variable Usage

Keep the following in mind while using API Catalog CLI:

* Command line options override environment variables. +
If you don't pass a command line option, the default profile properties are used.
* If not specified, the default environment is production.

=== Session Timeout

Your Anypoint session expires based on the *Default session timeout* configured in your Organization settings.

// Authentication end 

== Create or Update a Descriptor File Manually

You can create a descriptor file manually rather than using the `api-catalog create-descriptor` command to create it. You can also update a descriptor file that you have already generated to add conditions required to trigger the publish, add tags to APIs, control asset versioning, and so on.   

After you create the descriptor file, copy it to the file path or repository where your API projects are stored. 

The descriptor file must start with the following:

---

 #%Catalog Descriptor 0.6

---

TIP: Run the `api-catalog publish-asset` command using the `--dry-run` option to ensure that your manually-created descriptor file is valid. 

=== Descriptor YAML Schema

Following are the YAML tags used to describe the APIs you want to catalog. 

[%header,cols="20a,80a"]
|===
| Tag | Description 

| triggerConditions | This optional section enables you to set conditions to determine when to publish the set of APIs described in the descriptor file. If you add this section to the descriptor file, the APIs will be published only when the `api-catalog publish-asset` command is run with `--trigger` options with matching values for each of the trigger conditions. This enables you use the same `api-catalog publish-asset` command in your CI/CD scripts for each of your branches or environments and pass parameters to the command to control whether the APIs are published. 

---
 triggerConditions
  branch:
    - main
    - release/(.*)
  anytag:
    - support
    - release/(.*)
  user:
    - admin

---

The preceding example enables a run of the `api-catalog publish-asset` command to publish the APIs described by the descriptor file only if the command has all of the following three `--trigger` option values: 

* `branch` is `main` or has `release/` in the text
* `anytag` is `support` or has `release/` in the text
* `user` is `admin` 

If the `triggerConditions` section is included in the descriptor file, no APIS are published by the `api-catalog publish-asset` command unless all of the trigger conditions are matched by `--trigger` option values. For more information, see the `--trigger` option for the <<api-catalog publish-asset, `api-catalog publish-asset` command>> and <<Publish an Asset Using Trigger Conditions>>.

| contact | The contact name and email ID.   

| apis | A list of the APIs to be cataloged. 

spec:: The location of the specification file that describes the API. 

assetId:: Specifies the ID of the asset to be published in Exchange. 

docs:: A list of key and value pairs that specify the name of the documentation page and file location for the API.
These pairs define the order of the documentation pages in Anypoint Platform.
+
Format: <Name of the documentation page>:<File Location>
+
If this option is not specified, no documentation pages are imported. 

categories:: A list of key and value pairs that specify the category name and value. These pairs are validated against the categories that exist in the Anypoint Platform organization.
+
Format: <Category Name>: <Value(s)>
+
If this option is not specified, no categories are added.

customFields:: A list of key and value pairs that specify the field and value. These pairs are validated against the custom fields and field types that exist in the Anypoint Platform organization.
+
Format: <Field>: <Value(s)> 
+
If this option is not specified, no custom fields are added.

tags:: A list of free text strings. 
+
If this option is not specified, no tags are added.

versioning:: The asset version. 
+
If this is not specified, the patch version is incremented by one.
+
Example: ~1.x.x  
+
See <<Asset Versioning>>.

apiVersion:: The API version for the asset. 
+
If the API version is not specified in the descriptor file, the version from the specification file is used. If the API version is specified in both files, the value in the descriptor file is used. The value must be specified in one of the files. 
+
Example: v1  

|===

=== Asset Versioning

When you publish a version of an asset that already exists in Exchange, the patch version is incremented by default. However, you can set the version using semantic versioning notation `x.x.x` for major, minor, and patch versions respectively. 

Use the following symbols before the version nodes to control how an asset version is incremented:

[%header,cols="15a, 70a"]
|===
| Symbol

| Version Node

| ^ | patch

| ~ | minor

| & | major 

Because '&' is a reserved character in YAML, a semantic versioning string using this character must be enclosed in a single quote as follows: 

`'&x.x.x'`

|===

==== Examples of Asset Versioning

The following table shows how the asset version is incremented for example semantic versioning strings. 

[%header,cols="15a, 70a"]
|===
| Asset Version (versioning) 

| Explanation

| ^x.x.x (Default) | Search for the latest version and increment the patch

| ^1.x.x | Search for the latest version of major 1 and increment the patch

| ~1.x.x| Search for the latest version of major 1 and increment the minor

| ^1.0.x | Search for the latest version of major 1, minor 0 and increment the patch

| ^3.x.x | Search for the latest version of major 3 and increment the patch

| ^3.x.x | Search for the latest version of major 3 and increment the patch

| '&x.x.x' | Increment to the next the major version 

|===

For more information on asset versioning in Exchange, see xref:to-change-raml-version.adoc[Change the Version of an API Asset].

=== Example Descriptor File

Following is an example descriptor file that describes the cataloging information for two APIs. 

[source,yaml]
----

 #%Catalog Descriptor 0.6 # <1>
triggerConditions: # <2>
  branch:
    - main
    - release/(.*)
  anytag:
    - support
    - release/(.*)
  user:
    - admin
contact: # <3>
  name: 'John Doe'
  email: 'john.doe@org.com'
apis: # <4>
  - spec: api-spec/codat.json
    assetId: codat-api
    docs:
      add: api-spec/add.md
      home: home.md
    customFields:
      custom: value
      another: field
    tags:
      - codat
      - gcp
    versioning: 2.0.x
    apiVersion: v3
  - spec: api-spec/billing-api.json
    assetId: my-awesome-api
    tags:
      - finance
      - aws
    categories:
      API Type:
        - System API
        - Experience API
      Organization:
        - Finance
        - Billing
    versioning: ~1.x.x
    apiVersion: v1
----
<1> Provides the start line for the descriptor file
<2> Sets trigger conditions
<3> Provides the contact name and email ID 
<4> Specifies the API information to be published

== Configure Command Autocompletion

The `api-catalog-cli autocomplete` command enables you to configure completion for API Catalog CLI commands. 

To configure command autocompletion:

* If you are using a Bash shell:

. Run `api-catalog autocomplete bash`. This creates a cache and displays configuration and test instructions.
. Follow the instructions that are displayed by the command:
+
----
1) Add the autocomplete env var to your bash profile and source it
$ printf "eval $(api-catalog autocomplete:script bash)" >> ~/.bashrc; source ~/.bashrc

NOTE: If your terminal starts as a login shell you may need to print the init script into ~/.bash_profile or ~/.profile.

2) Test it out, e.g.:
$ api-catalog <TAB><TAB>                 # Command completion
$ api-catalog command --<TAB><TAB>       # Flag completion
----

* If you are using a Z shell:
. Run `api-catalog autocomplete zsh`. This creates a cache and displays configuration and test instructions.
. Follow the instructions that are displayed by the command:
+
----
1) Add the autocomplete env var to your zsh profile and source it
$ printf "eval $(api-catalog autocomplete:script zsh)" >> ~/.zshrc; source ~/.zshrc

NOTE: After sourcing, you can run `$ compaudit -D` to ensure that no permissions conflicts are present

2) Test it out, e.g.:
$ api-catalog <TAB>                 # Command completion
$ api-catalog command --<TAB>       # Flag completion
----

=== api-catalog-cli autocomplete

Following is a reference for the `api-catalog-cli autocomplete` command. 

*Usage*

----
$ api-catalog autocomplete [SHELL]
----

*Arguments*

----
SHELL shell type
----

*Options*

----
-r, --refresh-cache Refresh cache (ignores displaying instructions)
----

*Examples*

----
$ api-catalog autocomplete
$ api-catalog autocomplete bash
$ api-catalog autocomplete zsh
$ api-catalog autocomplete --refresh-cache
----

// == See Also

// * xref:anypoint-platform-cli-commands.adoc[Anypoint Platform CLI List of Commands]
