= API PL Video POC 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Getting Started with API Governance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

With API Governance you can:

* *Share governance best practices:* Catalog governance rulesets within
  Anypoint Exchange to share with other developers.
* *Apply consistent rules at design time:* Enable developers to apply
  governance rules at design time in Anypoint API Designer.
* *Enforce governance within your DevOps organization:* Automatically
  apply standards to your API contract and definition within your
  CI/CD pipeline.

IMPORTANT: If you do not see API Governance, it hasn't been added to your Anypoint
Platform instance yet. You can have it added by contacting MuleSoft and providing
your Organization Id. See xref:access-management::organization.adoc#manage-root-organization-settings[Manage Root Organization Settings]
for more information on how to find your Organization Id.

View the following video for a brief overview of how to use API Governance.  

++++
include::_partials/api-gov-for-api-video-temp.html[]
++++

Govern your APIs using the following steps: 

. xref:assign-api-gov-admins.adoc[Grant access to API Governance in Access Management].
+
Before you can access the API Governance component, you will need to have
API Governance Administrator privileges. You can add these privileges in
Access Management as you would add other privileges.

. xref:add-tags.adoc[Specify the APIs you want to govern in Exchange].
+
For the Beta, we recommend that you create special tags and add them to
a select group of APIs that you would like to use to experiment with API Governance.
Keep in mind when API Governance is applied to APIs, automated emails are sent
informing API owners if their APIs are not conformant and could cause alarm. Adding
tags before you begin the process of using API Governance ensures you can minimize
interruptions to a select group of API owners who can be informed in advance.

. xref:create-profiles.adoc[Select which rules to apply to which APIs in API Governance and the CLI].
+
Once you have access to API Governance and you have created tags to, the first step in governing your APIs is
creating a governance profile. Governance profiles pair rulesets with filter criteria to specify which
APIs in Exchange you want to govern and how you want to govern them. Governance profiles
can be added with the CLI as well.

. xref:monitor-api-conformance.adoc[Monitor your governance posture in API Governance and the CLI].
+
The API Governance console provides a visual reference for your API Conformance
posture so you can easily monitor and track which APIs are conformant
or need corrections. You can also send notifications to API authors, indicating
they need to update their API definitions to meet standards, and export
reports containing the status and details of each governance profile. Furthermore, you can
access governance profile information with the CLI as well.

. xref:add-rulesets.adoc[Find and correct conformance issues as you author API definitions in Design Center and the CLI].
+
You can add rulesets as dependencies to API definitions projects in
Design Center. Once added, you will see errors or warnings in the console
as you are writing your API definition. You can also validate ruleset format
and API definition conformance with the CLI.

. xref:upload-rulesets.adoc[Create Custom Rulesets in Anypoint Exchange and the CLI].
+
For the Beta, we have added MuleSoft Anypoint API Best Practices,
OpenAPI Best Practices, OWASP API Security Top 10, and Authentication
Security Best Practices rulesets to Exchange in advance. If you want
to add custom rulesets to Exchange, you would add them as any other
asset. You can also add rulesets with the CLI.


