//Use the MultiTopic template to document subjects that include a combination of topic types. This template includes all three topic types. Remove topic types that aren’t needed, or add additional topic types when needed. 

= Publish APIs Using API Catalog CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

== API Catalog CLI

API Catalog CLI enables you to publish APIs to Anypoint Exchange as they are created and updated as part of your CI/CD processes. 

== What You Can Do With API Catalog CLI

With API Catalog CLI you can:

* Publish API specifications in Exchange using CLI commands 
* Use descriptor files to explicitly define how you want the specifications to be published

For details, see the following:

* <<Install API Catalog CLI>>
* <<Create Descriptor Files>>
* <<Publish APIs Using CLI>>

== Install API Catalog CLI 

To enable developers in your organization to automatically publish the new API specifications, you must install API Catalog CLI and add it to your CI/CD pipeline. 

=== Prerequisites

* Download and install NodeJS and npm (node package manager) on your system.
+
See the https://nodejs.org/en/download/[NodeJS download page].
* Download and install the Git version management on your system.
+
See the https://git-scm.com/downloads[Git download site].

Depending on the configuration of your system, you might need to run these commands using administrator credentials.

[source,text,linenums]
----
$ npm install -g anypoint-cli@latest
----

If the installation command fails with the following error, ensure that the Git client is installed on your computer and the git protocol is not blocked by your firewall or network:

[source,text,linenums]
----
fatal: read error: Invalid argument
----

If the git protocol is blocked, you can configure Git to use `https://` instead of `git://`:

[source,text,linenums]
----
git config --global url."https://".insteadOf git://
----

System Requirements:

* Anypoint Platform account
* Anypoint Platform user account

=== Install the CLI

To install the CLI:

. Download the API Catalog CLI package from the xref:https://npmjs.com[npm public registry]. 
. Run the following command from your terminal, where <API-Catalog-CLI-package-name> is the name of the package you downloaded:
----
npm install -g <API-Catalog-CLI-package-name>@beta
----

To give access to the CLI from any directory:
----
$ npm link
$ cd ../<your-directory-name>
$ api-catalog-cli publish-asset
----

== Create Descriptor Files

Before you run the commands to publish your APIs, you must create a descriptor file in each of the Git repositories you are using for your CI/CD processes. You can use the following approaches:

* *Dry Run Mode*: Use this mode to run the publish catalog command with an empty descriptor.yaml file and get a preview in your CI/CD log of the APIs that would be cataloged. 
* *Explicit Mode*: Use this mode to run the publish catalog command with a complete descriptor file that specifies the APIs that should be cataloged. 

=== Dry Run Mode

Use dry run mode to generate content for a starter descriptor file and discover which APIs are available in a CI/CD repository that are candidates to be cataloged in Exchange. The CI/CD job sends results to standard output. The output has suggested descriptor file content and status messages, such as lists of APIs that would not be cataloged based on this descriptor content.
No API specifications or documentation are cataloged in Exchange.

To use dry run mode:

. Add an empty +descriptor.yaml+ file to your Git repository. 
. Modify your CI/CD pipeline to add the following command: 
. Run the CI/CD pipeline.
. Check your CI/CD log for the results.
. Update the +descriptor.yaml+ file in your Git repository with the content from the dry run and modify as needed. 

=== Explicit Mode

Use explicit mode when you have descriptor file content that identifies the APIs that you want to publish in Exchange. You can use dry run mode to obtain suggested content from your CI/CD repository or you can create the descriptor file by using the following documentation. 

*Syntax*

<...>

Although you can enter authentication credentials explicitly in the commands for testing purposes, you should use secure authentication in your CI/CD environment.

See <<Authentication>>.

*View Command Help*

<...>

*Specify the Version Rules*

<...>  

=== Example Descriptor File

<...>

== Add the Descriptor File to Your Repositories

After you install API Catalog CLI, you must add the descriptor file, with the file name and location specified by your DevOps admin, to the repositories that you want to integrate with the publishing process.

*Prerequisites*

Before you add the descriptor file to the repository, ensure that:
API Catalog CLI is installed in your CI/CD pipeline 
For details on how to perform this installation, see <xref>. 
You have the repository location where you want to add the descriptor file ready.

To add a descriptor file to a repository:

<...>

== Publish APIs Using CLI
You can publish your APIs to Anypoint Exchange with API Catalog CLI commands. To automate the publishing of APIs using CLI, you will typically use build scripts in tools such as Jenkins, but you can run the CLI manually from a terminal for learning and testing purposes. 

=== Syntax 

<...>

=== View Command Help

<...>

=== Specify the Version Rules

<...>  

For information on passing credentials, see <<Authentication>>.

== Example API Catalog CLI Command

The following example publishes the API to the ‘4c06ba7b-3ce8-425c-878c-b728dd7db60d’ organization in the US control plane using the ./catalog.yaml descriptor file in the master branch of the VCS repository:

api-catalog-cli publishAsset -o c06ba7b-3ce8-425c-878c-b728dd7db60d  -a https://anypoint.mulesoft.com/


In the example, an assumption is made that either the username and password credentials are defined in the ANYPOINT_USERNAME and ANYPOINT_PASSWORD environment variables or that the client ID and client secret credentials are already defined.

<...>

== Example Jenkins Script 

An example Jenkins script that runs the commands is as follows:

<Example Jenkins script>

== Authentication

You can configure Anypoint CLI authentication with username and password, client ID and client secret, or a bearer token.
At least one method is required.

=== Username and Password

If you don't log in using single sign-on (SSO), you can use your username and password to log into the CLI directly.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `username` | Your Anypoint Platform username

You can also pass this value using the environment variable `export ANYPOINT_USERNAME=<name>`.
| `password` | Your Anypoint Platform password

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>`.
|===

For information about logging in using SSO, see xref:access-management::external-identity.adoc[About Identity Management].

=== Client ID and Client Secret

You can configure a Connected App with the `client_credentials` grant type to use with the CLI.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `client_id` | The ID of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_ID=<client_id>`.
| `client_secret` | The client secret of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_SECRET=<client_secret>`.
|===

For more information about Connected Apps, see xref:access-management::connected-apps-overview.adoc[Connected Apps].

=== Reference

API Catalog CLI takes the following optional arguments:

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter |Description
| `organization` | Your organization within Anypoint Platform

You can also pass this value using the environment variable `export ANYPOINT_ORG=<name>`.

| `environment` | Your Anypoint Platform environment

You can also pass this value using the environment variable `export ANYPOINT_ENV=<name>`.

| `host` | The host of your Anypoint Platform Installation +
By default, this value points to `\https://anypoint.mulesoft.com`. +

* If you are using Anypoint Platform PCE, pass the address where you are hosting the platform.
* If you are using Anypoint Platform EU Cloud, pass your EU control plane URL.

You can also pass this value using a dedicated environment variable `ANYPOINT_HOST=<name>`.

|===

=== Usage

Keep the following in mind while using API Catalog CLI:

. Command-line parameters override environment variables. +
If you don't pass a command-line parameter, the default profile properties are used.
. If not specified, the default environment is production.
+
. Your Anypoint session expires based on the *Default session timeout* configured in your Master Organization settings.

// Authentication end 

== See Also

* xref:anypoint-platform-cli-commands.adoc[Anypoint Platform CLI List of Commands]
Anypoint Exchange
