= Creating or Updating Descriptor Files Using the CLI

Before you run the commands to publish your APIs, you must create a descriptor file that has the information Exchange needs to catalog the APIs. Typically you create the file using the CLI and then update the file manually to set more options to control how the assets are published. 

The output descriptor information includes the following for each API:

* API definition file name
* Asset ID
* Asset version
* API version

== Create a Descriptor File

Use the `api-catalog create-descriptor` command to identify and output the API catalog descriptor YAML results to a designated file. The command outputs cataloging information for all API definitions it finds in the full directory tree relative to the current working directory.

To create a descriptor file using the CLI:

. Navigate to the directory path that contains the APIs you want to catalog. 
. Run the `api-catalog create-descriptor` command. The following example creates a descriptor file called `mydescriptor.yaml` in the current path:
+
----
> api-catalog create-descriptor -d mydescriptor.yaml
----
+
Example output that is written to the descriptor file:
+
----
#%Catalog Descriptor 0.7
projects:
 - main: async-spec.json
  assetId: async-test
  version: 2.0.0
  apiVersion: v2
 - main: codat.json
  assetId: codat-api
  version: 1.0.0
  apiVersion: v1
 - main: oas-3-spec.json
  assetId: oas-3-test
  version: 3.0.0
  apiVersion: v3
----

The result of the command depends on the presence and content of the designated descriptor file as follows:

* No file or empty file: The command discovers the APIs and writes the results to standard output and to a file named `catalog.yaml`.

* Existing file with content: The command fails and shows an error message that says the descriptor file already exists.

//include::anypoint-cli::partial$api-catalog.adoc[tag=create-descriptor-command]

include::partial$api-catalog.adoc[tag=create-descriptor-command]

== Update a Descriptor File

Use the `api-catalog update-descriptor` command to update the API catalog descriptor YAML results in a designated file. The command adds and updates cataloging information for all new and updated API definitions it finds in the full directory tree relative to the current working directory.

To update a descriptor file using the CLI:

. Navigate to the directory path that contains the APIs you want to catalog. 
. Run the `api-catalog update-descriptor` command. The following example updates a descriptor file called `mydescriptor.yaml` in the current path:
+
----
> api-catalog update-descriptor -d mydescriptor.yaml
----

The result of the command depends on the presence and content of the designated descriptor file as follows:

* No file or empty file: An error message is shown because the update requires that a valid descriptor file exists. 

* Existing file with content: The command compares the APIs in the directory path to the list of APIs in the descriptor file and updates the descriptor file with new and updated API information.

//include::anypoint-cli::partial$api-catalog.adoc[tag=update-descriptor-command]

include::partial$api-catalog.adoc[tag=update-descriptor-command]

== See Also

* xref:apicat-use-api-catalog-cli.adoc[Using API Catalog CLI]
* xref:apicat-publish-using-api-catalog-cli.adoc[Publishing Assets Using API Catalog CLI]
* xref:apicat-create-descriptor-file-manually.adoc#manual-descriptor[Creating or Updating Descriptor Files Manually]