= Autocataloging APIs Using API Catalog CLI

API Catalog CLI enables you to discover and catalog your API specifications, documentation files, and associated metadata as part of an automated process. You can embed the publish asset command in your automation tools, such as a CI/CD pipeline or custom scripts, to automatically trigger the cataloging of your API assets. API Catalog CLI is agnostic of CI/CD tools and runtime environments.

With API Catalog CLI you can:

* Identify all APIs in a project directory structure and create a descriptor file to use to publish the APIs to Exchange.
* Identify all new and changed APIs and update the descriptor file on an ongoing basis. 
* Conditionally trigger the publish based on criteria such as branches and tags.
* Conditionally set the asset version strategy based on criteria such as branches and tags.
* Publish APIs described in the descriptor file locally or as part of your automation tools.

== API Catalog CLI Concepts

Following are the concepts you need to know to use API Catalog CLI.

[[apicat-autocatalog]]
=== Autocatalog

xxx

[[apicat-descriptor]]
=== Descriptor

xxx

[[apicat-exchange-json]]
=== exchange.json

xxx

[[apicat-publish]]
=== Publish

xxx

[[apicat-trigger]]
=== Trigger

xxx

[[apicat-trigger]]
=== Version Strategy

xxx

== See Also

* xref:apicat-get-started.adoc[Getting Started with API Catalog CLI]