= Asset Usage and Engagement Metrics Dashboard
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Exchange administrators can view usage and engagement metrics using the dashboard. The usage metrics measure how many times an asset is downloaded from Exchange, imported from API Designer, and imported from Studio. The asset engagement score is a composite metric that administrators and asset owners can use to measure the usage of the assets in Exchange. The results for this engagement are the different consumption actions that end-users make across different points of need within Exchange. The engagement score of an asset reflects the usage of the asset in the context of the usage for all assets in the customer root organization and business groups. 

The dashboard displays the metrics for the top assets for a period of the last 7 days, 30 days, or 60 days that are ranked by the most consumption events. You can filter the top assets by API Specification and REST API types and by one or more organizations. Export metric data into a CSV file by clicking CSV to Export.

The following graphic shows the Usage and engagement metrics dashboard: 

//placeholder for graphic

The following data is collected and analyzed:

* Rank
+
Assets ranked by the most number of consumption events for RAML fragments and REST APIs.
* Name
+
The name of the asset.
* Organization
+
The name of the business organization that the asset belongs to. 
* Created on
+
The date that the asset was created.
* Last updated
+
The date that the asset was last updated.
* Engagement score
+
The engagement score reflects the usage of the asset in context of usage of all assets in the customer root organization and business groups.
* Downloads
+
The number of times the asset was downloaded. You can sort by ascending or descending order. 
* Imports from API Designer
+
The number of times the asset was imported into Design Center. You can sort by ascending or descending order.
* Imports from Studio
The number of times the asset was imported into Studio.
* All-time Stats
** Dependents
+
The number of dependent assets since the version was created.
** Contracts
+
The number of approved contracts since the version was created.

== Viewing Asset Usage and Engagement Metrics 
To view the data you need, refine the asset *Usage and engagement metrics* dashboard by selecting date ranges and filtering by asset type and organization.

To view metrics:

. In the navigation bar in Exchange, click *Asset engagement*.
. Select a date range from 7 days, 30 days, or 60 days.
+
The default date range is the last 7 days.
. To filter by asset type, from *Asset Type*, select an option.
. To filter by an organization, from *Any Organization*, either enter the name of an organization or check one or more organizations, then click *Apply*.
+
The dashboard populates with the filter criteria.
. To view metrics for a specific asset in the list of the dashboard, click the link next to the asset name.
+
The asset details page displays the usage and engagement metric information. 
. To view the dependents of an asset, click the *Dependents* row that contains one or more dependents.
+
A dialog shows the list of version dependents for that asset. 
. To export the usage data, click *Export to CSV*.
