= Search API Specification and Asset Pages
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

The assets details page enables you to find specific information within the pages and API specification of an asset using the CTRL+F or the command+F keyboard shortcut. In Exchange, this enhanced shortcut overrides the native browser shortcut, which only searches for words and phrases on the current page. To quickly find the information you need, use this enhanced shortcut to search the content of every page and the API specification of an asset.

To search pages and the API specification using the enhanced find shortcut:
  
. In the asset details page, press CTRL+f or command+f.
. . In the *Search content* box, enter a search term or phrase.
. Click a search result from the list.
. Use the up and down arrows to move through all the occurrences of the search term within the search results.
. Click the *X* to close the Search content box.

The enhanced keyboard shortcut looks for terms or phrases in:

* Pages
* Home
* Additional pages
* Specification
** Summary
** Endpoints
** Documentation
** Types
** Security

When you enter a search term or phrase in the search box, the search results box displays the sections within Pages and Specification that contain the search terms entered. Click the search result to open the page with the search term or phrase highlighted. The search result shows the number of search-term matches in each page. Use the arrows to move up or down in the list of search results and to the next page.

For example, enter the term *ruleset* in the Search content box. Under Pages, there are three search results for ruleset in the Home page. Click *Home* to open the page. Use the up and down arrows to find all of the highlighted instances of ruleset in the Home page.
