= Generating API Documentation With Einstein Generative AI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Use Einstein generative AI to generate API documentation for REST APIs in Exchange, and streamline how your organization manages APIs. By using AI technologies, developers can simplify API documentation processes. AI creates API documentation that is consistent, accurate, and current. This frees developers to focus on strategic tasks and enhances developer satisfaction.

You can create documentation for single file REST APIs that don’t have any documentation. From the asset details page, generate the documentation, then manually edit and improve the documentation after it’s generated. After that, publish it to make it available to everyone in your organization.

This release supports:

* REST APIs only
* Single file format only
* Multi-format files and fragments aren’t supported
* REST APIs published from Exchange only

APIs published to Exchange from other products like Anypoint Code Builder and Anypoint Design Center aren’t supported.


//placeholder for screen capture of asset details page

== Documentation Structure
AI-generated documentation in Anypoint Exchange standardizes API documentation, addressing inconsistency and incompleteness. The structure of the generated documentation is standardized across each API including fonts, headers, text size.

Generated documentation includes:

* Overview and purpose of the API
* Authentication requirements and security details
* Base URL and environments
* Detailed endpoint documentation including:

** Request and response examples 
** Query parameters
** Path parameters
** Request body schemas
** Response codes and examples
* Error handling and status codes
* Best practices for implementation
* Sample code snippets

== Before You Begin
Before generating API documentation with Einstein, you must have:

* Salesforce Org or Trial account with Einstein enabled in Anypoint Platform.
+
To enable Einstein in Anypoint Platform, see xref::access-management:enabling-einstein.adoc#enable-einstein-anypoint[Enable Einstein for Your Anypoint Platform Organization].

* Einstein credits because this feature uses Salesforce Einstein Large Language Model (LLM).

== Generate API Documentation with Einstein
Generate documentation for REST APIs published from Exchange without documentation.

. Select the API from the catalog and click *Generate Documentation* from the asset details page.
. Review the generated documentation in draft mode and save the draft or publish it.
//placeholder for screen capture of asset details page with editor
. To edit the documentation, click *Edit*, make your changes, and save the draft or publish it.
//placeholder for screen capture of asset details page with editor
+ 
Publishing the documentation makes it available to everyone in your organization.

See xref:to-describe-an-asset#edit-asset-portal-documentation[Edit Asset Documentation], for more information about editing asset documentation.







