= Importing Agentforce Agents
:page-support-status: eolReachedFeature
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

NOTE: Importing Agentforce agents from *Settings* is no longer supported. To import Agentforce agents, create an Agentforce scanner. For more information, see xref:adding-agentforce-scanner.adoc[].

Organizations can import their Agentforce agents into Exchange to include them in business groups.

Importing from the same Salesforce organization into a different business group can create duplicate assets in Exchange.

Imported Agentforce agents appear in *Agents & Tools*.

== Before You Begin
Before importing Agentforce agents, complete these requirements:

* xref:access-management::managing-connected-salesforce-orgs.adoc#enable-disable-connection[Enable the connection to a Salesforce organization] that has an established tenant relationship with your Anypoint Platform organization.
* xref:access-management::enabling-einstein.adoc[Enable Einstein in Anypoint Platform]
+
Accept the terms and conditions and set a default organization for Einstein.

== Import Agentforce Agents

. Select *Settings* from the sidebar and then select the *Asset Import* tab.
. Click *Import Agents* and then click *Confirm*.
+
Agents are imported in the current business group.
. Close the dialog and refresh the page after a few minutes.
. Verify that the Agentforce agents are listed in the Exchange catalog on the *Agents & Tools* page.

== See Also

* xref:adding-agentforce-scanner.adoc[]