= Anypoint Exchange
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/
:page-aliases: general:getting-started:anypoint-exchange.adoc

Discover and share assets and resources available on Anypoint Exchange, and reuse them in your applications and APIs.

In addition to Anypoint Exchange, the public instance managed by MuleSoft, other instances of Exchange include:

* Your Anypoint Platform organization has a private Exchange where you can share assets within your organization.
* You can also create public portals, instances of Exchange that you can make available to the public.

In all these instances of Exchange, you can view and test APIs, simulate data to APIs (Mocking Service), create assets, and use API Notebooks to describe and test API functions.

== Get Started

Explore Anypoint Exchange, which is visible to all, or check to see if you have any public portals,
instances of Exchange created within your Anypoint Platform organization.

=== Find Resources on Anypoint Exchange

. Visit https://www.anypoint.mulesoft.com/exchange/[Anypoint Exchange].
. Scroll to view assets.
. Click on an asset to view its description. If you log into Anypoint Platform, you can download an asset.
. Optionally, search for assets by type.

=== Find Resources in a Public Portal

A public portal is an instance of Anypoint Exchange created
within your Anypoint Platform organization.

If someone has already created a public portal you can explore it:

. Log in to your Anypoint Platform account.
. Click Public Portal in your organization.
. View APIs and other assets just as you did in Anypoint Exchange.

=== Try APIs

. From Anypoint Exchange or a public portal, click All Types > REST APIs and choose any API.
. Click the asset and notice how the API functions appear in the left
navigation area. Exchange lets you view the functions in an API.
. Click a function and more information appears. At the right side of the screen, you can test the API by entering sample values to send to the API and get responses from the API.
. Click the Helpful Links item in the left navigation area for links to documentation.

== Learn More About Exchange

Exchange assets are accessible in Anypoint Studio (connectors, templates, and examples), API Manager (APIs, API Groups, and policies), and Runtime Manager (APIs), and you can publish APIs from Design Center to Exchange.

MuleSoft certifies public content, and reviews and approves partner connectors, published in Anypoint Exchange.
Private content is internal to an organization and not visible outside that organization.
Each organization is responsible for private content published in their Exchange instance or public portal.

=== Language Support

Using multiple languages with Unicode is supported fully throughout Exchange and in all metadata fields, including asset names, descriptions, markdown pages, categories, tags, and reviews.

[[content-types]]
=== Content Types

Both the public and private content in Exchange can consist of the following kinds of elements:

* Connectors - Packaged connectivity to an endpoint developed and deployed on Anypoint Platform with third-party APIs and standard integration protocols
+
Use connectors within your application's flows to send and receive data using a protocol or specific API. Anypoint Studio comes with many bundled connectors, and Exchange has many more.
* Templates - Packaged integration patterns built on best practices to address common use cases
+
You can add your information such as user credentials to complete the template's use case or solution, and you can customize or extend templates as needed.
* Examples - Applications that are ready to run in Anypoint Studio and demonstrate a use case or solution
* Policies - Configuration modules to extend the functionality of an API and enforce capabilities such as security
* REST APIs - A RAML file or OAS file that specifies an API
+
These APIs can be referenced by an HTTP Request connector to expose metadata to Anypoint Studio.
* SOAP APIs - A WSDL file that specifies an API
* HTTP APIs - A placeholder for an endpoint for use by private Exchange users who want to manage the endpoint with API Manager
* API Groups - A set of APIs bundled into a single asset
+
Instead of requesting access to multiple APIs to satisfy a use case, a developer can access the group in one step.
* API Spec Fragments - A RAML document that has a version and an identifier, but is not in itself a complete RAML specification
+
API spec fragments are also known as RAML fragments.
* Custom - A description and an optional file to explain aspects of your system, to provide instructional videos, or to describe product or organizational documentation

== Deprecated Exchange

You may find an earlier version of Anypoint Exchange while searching the Internet.
New content isn't published to this version, and is available to assist migration to the current Exchange version documented here.

== What's Next?

After you log into Exchange, you can create assets for APIs, connectors, templates, examples, API Notebooks, and custom assets.

== See Also

* xref:release-notes::exchange/anypoint-exchange-release-notes.adoc[Anypoint Exchange Release Notes]
* xref:about-exchange1.adoc[About Exchange 1 (Old Version)]
* xref:migrate.adoc[Migrate Assets from Exchange 1]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://help.mulesoft.com[MuleSoft Help Center]
