[install-cat-cli]
= Install and Configure API Catalog CLI 

To enable developers in your organization to automatically publish the new API specifications, you must install API Catalog CLI. API Catalog is included in Anypoint CLI 4.0 and later. You can install just the API Catalog plugin if you do not already have Anypoint CLI installed and do not have an immediate need for other Anypoint CLI commands.

== Prerequisites

* Download and install the latest LTS version of NodeJS and npm (node package manager) on your system. See the https://nodejs.org/en/download/[NodeJS download page^]. 

== Full Anypoint CLI Installation

To install the CLI:

* Run the following command from your terminal:
----
npm install -g anypoint-cli@latest
----

== API Catalog CLI Installation Only

To install the API Catalog CLI plugin:

* Run the following command from your terminal:
----
npm install -g api-catalog-cli@latest
----

NOTE: The install command might give warning messages about the version of npm because the API Catalog CLI installation package is built using npm version 14. You can ignore these messages. 