= Manage Asset Lifecycle States
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

In the software development lifecycle, assets are developed, released, and eventually deprecated, and each Exchange asset version moves through the lifecycle states of `development`, `stable`, and `deprecated`.

== Development State

An asset version in the `development` state is in an iterative process of design and development.

If you re-publish an asset version in the `development` state with the same groupId, assetId, and version (GAV) and new metadata, the asset version is overwritten, including this asset version metadata:

* files
* dependencies
* keywords

Changing this information for an asset version in any other state requires creating a new version, which prevents re-publishing or overwriting the asset version.

Overwriting an asset version also updates the search index.

The Exchange user interface and APIs change some asset version information for asset versions in any state. This information is not changed by overwriting an asset version in the `development` state. This information includes:

* tags
* categories
* custom fields
* documentation pages

Deleting an asset version in the `development` state is always a hard delete, enabling you to reuse the asset's name, groupId, assetId, and version.

The public portal does not show asset versions in the `development` state.

Anypoint Platform products other than Exchange, such as Anypoint API Designer, Anypoint Flow Designer, or Anypoint Studio, do not consume asset versions in the `development` state.

== Stable State

An asset version in the `stable` state is ready to use. It is not possible to re-publish or overwrite it.

Deleting an asset version in the `stable` state in the first seven days is a hard delete, enabling you to reuse the asset's name, groupId, assetId, and version. Deleting an asset version in the `stable` state after the first seven days is a soft delete, preventing you from reusing the asset's name, groupId, assetId, and version. After a hard delete or a soft delete, an asset cannot be recovered or undeleted.

The Exchange backend and some API responses use the term `published` to mean `stable`.

== Deprecated State

An asset version in the `deprecated` state is similar to an asset version in the `stable` state. The only difference is that the `status` property shows the asset version is deprecated.

== Create an Asset in the Exchange User Interface

. Click *Publish new asset*.
. Set *Lifecycle state* to the *Development* state or the default *Stable* state.
. Set other asset information.
. Click *Publish*.

== State Promotion

These are the three possible state promotions:

. `development` to `stable`
. `stable` to `deprecated`
. `deprecated` to `stable`

Promote an asset version's state either in the asset's Exchange portal or by using the Exchange API.

In the asset's portal, click the lifecycle state button that displays the current state, and select the new state of *Development*, *Stable*, or *Deprecated*.

In this Exchange API example, replace `ANYPOINT_TOKEN`, `:groupId`, `:assetId`, and `:version` with your information, and replace `:status` with `development`, `published`, or `deprecated`.

[source,console]
----
curl -X https://anypoint.mulesoft.com/exchange/api/v2/assets/:groupId/:assetId/:version/status \
    -H 'Authorization: bearer ANYPOINT_TOKEN' \
    -d '{"status": ":status"}'
----

== Create an Asset Using the Exchange API

A new asset version is in the `development` state or the default `stable` state. The `stable` state is also known as `published`. An asset version must be in the `stable` state before it is in the `deprecated` state.

To use the Exchange API version 2 to create an asset and set its lifecycle state, add the property `status` to the multipart request when you follow the steps in xref:exchange-api.adoc[Publish Assets Using the Exchange API]. If the state is not specified, the asset is created with the default `stable` state.

REST API asset example:

. Log in to Anypoint Platform and download the https://anypoint.mulesoft.com/exchange/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/assets/68ef9520-24e9-4cf2-b2f5-620025690913/training-american-flights-api/1.0.0/files/fat-raml/zip[example file].
. Replace `/file-path/training-american-flights-api-1.0.0-raml.zip` with the local path of the downloaded file.
. Replace `ANYPOINT_TOKEN`, `:organizationId`, `:groupId`, `:assetId`, and `:version` with your information.
. Set the property `status` to `development` or `published`.
. Execute:

[source,console]
----
curl -v \
    -H 'Authorization: bearer ANYPOINT_TOKEN' \
    -H 'x-sync-publication: true' \
    -F 'name=RAML asset name' \
    -F 'description=Description of the asset' \
    -F 'keywords=best, raml' \
    -F 'status=development' \
    -F 'properties.mainFile=american-flights-api.raml' \
    -F 'properties.apiVersion=v1' \
    -F 'files.raml.zip=@/file-path/training-american-flights-api-1.0.0-raml.zip' \   https://anypoint.mulesoft.com/exchange/api/v2/organizations/:organizationId/assets/:groupId/:assetId/:version
----

To use the Exchange API version 1 to create an asset and set its lifecycle state, send the status property as a field.

== Create an Asset Using Maven

A new asset version is in the `development` state or the default `stable` state.

To create an asset version in the `stable` state, follow the steps in xref:to-publish-assets-maven.adoc[Publish Assets Using Maven].

To create an asset version in the `development` state, use the Anypoint Exchange Maven Facade API version 3 and set the version of the asset to `SNAPSHOT`.

A `SNAPSHOT` asset is permanently in the `development` state and cannot be promoted to any other state.

An asset with the version `SNAPSHOT` published with the Anypoint Exchange Maven Facade API version 1 or version 2 has the state `stable`.

Uploading a `SNAPSHOT` template asset in the `development` state example:

In a terminal:

. Execute: `git clone https://github.com/mulesoft-labs/exchange-documentation-samples.git`
. Execute: `cd exchange-documentation-samples/template-snapshot`
. Edit the file `pom.xml` and replace the values `YOUR_ORG_ID`, `YOUR_GROUP_ID`, and `YOUR_ASSET_ID` with your asset's organizationId, groupId, and assetId.
. Execute: `mvn clean deploy`
. Open your Exchange home page and view the template in the `development` state.

If you execute `mvn clean deploy` multiple times, the asset is overwritten without any errors.

== Search Using the Graph API by Lifecycle State

To consume an asset and its lifecycle state, replace `ANYPOINT_TOKEN`, `:groupId`, `:assetId`, and `:version` with your information, and execute this command:

[source,console]
----
curl -X POST \
  https://anypoint.mulesoft.com/graph/api/v2/graphql \
  -H 'Authorization: bearer ANYPOINT_TOKEN' \
  -H 'content-type: application/json' \
  -d '{"query":"{asset(groupId: \":groupId\",assetId: \":assetId\",version: \":version\"){groupId assetId version status}}"}'
----

To search for an asset by lifecycle state, replace `ANYPOINT_TOKEN` with your information, replace `[development, published, deprecated]` with your list of desired lifecycle states, and execute this command:

[source,console]
----
curl -X POST \
  https://anypoint.mulesoft.com/graph/api/v2/graphql \
  -H 'Authorization: bearer ANYPOINT_TOKEN' \
  -H 'content-type: application/json' \
  -d '{"query":"{assets(status:[development, published, deprecated]){groupId assetId version status}}"}'
----

== See Also

* xref:to-delete-asset.adoc[Delete an Asset]
* xref:exchange-api.adoc[Publish Assets Using the Exchange API]
* xref:to-publish-assets-maven.adoc[Publish Assets Using Maven]
* xref:to-search-with-graph-api.adoc[Search Using the Graph API]
* https://anypoint.mulesoft.com/graph/api/v2/graphql[Graph API Web Interface]
