= Manage Asset Lifecycle States
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

In the software development lifecycle, assets are developed, released, and eventually deprecated, and each Exchange asset version moves through the lifecycle states of `development`, `stable`, and `deprecated`.

== Development State

An asset version in the `development` state is in an iterative process of design and development.

If you re-publish an asset version in the `development` state with the same groupId, assetId, and version (GAV) and new metadata, the asset version is overwritten, including this asset version metadata:

* files
* dependencies
* keywords

Changing this information for an asset version in any other state requires creating a new version, which prevents re-publishing or overwriting the asset version.

Overwriting an asset version also updates the search index.

The Exchange user interface and APIs change some asset version information for asset versions in any state. This information is not changed by overwriting an asset version in the `development` state. This information includes:

* tags
* categories
* custom fields
* documentation pages

Deleting an asset version in the `development` state is always a hard delete, enabling you to reuse the asset's name, groupId, assetId, and version.

The public portal does not show asset versions in the `development` state.

Anypoint Platform products other than Exchange, such as Anypoint API Designer, Anypoint Flow Designer, or Anypoint Studio, do not consume asset versions in the `development` state.

== Stable State

An asset version in the `stable` state is ready to use. It is not possible to re-publish or overwrite it.

Deleting an asset version in the `stable` state in the first seven days is a hard delete, enabling you to reuse the asset's name, groupId, assetId, and version. Deleting an asset version in the `stable` state after the first seven days is a soft delete, preventing you from reusing the asset's name, groupId, assetId, and version. After a hard delete or a soft delete, an asset cannot be recovered or undeleted.

The Exchange backend and some API responses use the term `published` to mean `stable`.

== Deprecated State

An asset version in the `deprecated` state is similar to an asset version in the `stable` state. The only difference is that the `status` property shows the asset version is deprecated.

== Create an Asset in the Exchange User Interface

. Click *Publish new asset*.
. Set *Lifecycle state* to the *Development* state or the default *Stable* state.
. Set other asset information.
. Click *Publish*.

== State Promotion

These are the three possible state promotions:

. `development` to `stable`
. `stable` to `deprecated`
. `deprecated` to `stable`

Promote an asset version's state either in the asset's Exchange portal or by using the Exchange API.

In the asset's portal, click the lifecycle state button that displays the current state, and select the new state of *Development*, *Stable*, or *Deprecated*.

To use the Exchange API, follow the xref:exchange-api.adoc#promote-lifecycle-state[Promote Lifecycle State] example.

== Create an Asset Using the Exchange API

To create an asset using the Exchange API, follow the xref:exchange-api.adoc#set-lifecycle-state[Set Lifecycle State] example.

== Create an Asset Using Maven

To create an asset using the Exchange Maven Facade API, follow the xref:to-publish-assets-maven.adoc#asset-lifecycle-state[Asset Lifecycle State] example.

== Search Using the Graph API by Lifecycle State

To consume an asset and its lifecycle state, replace `ANYPOINT_TOKEN`, `:groupId`, `:assetId`, and `:version` with your information, and execute this command:

[source,console]
----
curl -X POST \
  https://anypoint.mulesoft.com/graph/api/v2/graphql \
  -H 'Authorization: bearer ANYPOINT_TOKEN' \
  -H 'content-type: application/json' \
  -d '{"query":"{asset(groupId: \":groupId\",assetId: \":assetId\",version: \":version\"){groupId assetId version status}}"}'
----

To search for an asset by lifecycle state, replace `ANYPOINT_TOKEN` with your information, replace `[development, published, deprecated]` with your list of desired lifecycle states, and execute this command:

[source,console]
----
curl -X POST \
  https://anypoint.mulesoft.com/graph/api/v2/graphql \
  -H 'Authorization: bearer ANYPOINT_TOKEN' \
  -H 'content-type: application/json' \
  -d '{"query":"{assets(status:[development, published, deprecated]){groupId assetId version status}}"}'
----

== See Also

* xref:to-delete-asset.adoc[Delete an Asset]
* xref:exchange-api.adoc[Publish Assets Using the Exchange API]
* xref:to-publish-assets-maven.adoc[Publish Assets Using Maven]
* xref:to-search-with-graph-api.adoc[Search Using the Graph API]
* https://anypoint.mulesoft.com/graph/api/v2/graphql[Graph API Web Interface]
