= Asset Lifecycle States
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

In the software development lifecycle, assets are developed, released, and eventually deprecated, and each Exchange asset version moves through the lifecycle states of `development`, `stable`, and `deprecated`.

In all examples, replace these fields:

* `ANYPOINT_TOKEN`
* `organizationId`
* `groupId`
* `assetId`
* `version`

== Development State

An asset version in the `development` state is in an iterative process of design and development.

If you re-publish an asset version in the `development` state with the same groupId, assetId, and version (GAV) and new metadata, the asset version is overwritten, including this asset version metadata:

* files
* dependencies
* keywords

Overwriting an asset version also updates the search index.

Changing this information for an asset version in any other state requires creating a new version, which prevents re-publishing or overwriting the asset version.

The Exchange user interface and APIs change some asset version information for asset versions in any state. This information is not changed by overwriting an asset version in the `development` state. This information includes:

* tags
* categories
* custom fields
* documentation pages

Deleting an asset version in the `development` state is always a hard delete, enabling you to reuse the asset's name, groupId, assetId, and version.

The public portal does not show asset versions in the `development` state.

Anypoint Platform products other than Exchange, such as Anypoint API Designer, Anypoint Flow Designer, or Anypoint Studio, do not consume asset versions in the `development` state.

== Stable State

An asset version in the `stable` state is ready to use. Re-publishing and overwriting it are not possible.

Deleting an asset version in the `stable` state in the first seven days is a hard delete, enabling you to reuse the asset's name, groupId, assetId, and version. Deleting an asset version in the `stable` state after the first seven days is a soft delete, preventing you from reusing the asset's name, groupId, assetId, and version. After a hard delete or a soft delete, an asset cannot be recovered or undeleted.

The Exchange backend and some API responses use the term `published` to mean `stable`.

== Deprecated State

An asset version in the `deprecated` state is similar to an asset version in the `stable` state. The only difference is that the `status` property shows the asset version is deprecated.

== State Promotions

These are the three possible state promotions:

. `development` to `stable`
. `stable` to `deprecated`
. `deprecated` to `stable`

Promote an asset version's state either in the asset's Exchange portal or by using the Exchange API.

In this Exchange API example, replace `status` with `development`, `published`, or `deprecated`.

[source,console]
----
curl -X https://anypoint.mulesoft.com/exchange/api/v2/assets/:groupId/:assetId/:version/status \
    -H 'Authorization: bearer ANYPOINT_TOKEN' \
    -d '{"status": ":status"}'
----

== Create an Asset by Using the Exchange API

A new asset version is in the `development` state or the default `stable` state. The `stable` state is also known as `published`. An asset version must be in the `stable` state before it is in the `deprecated` state.

To use the Exchange API to create an asset and set its lifecycle state, add the property `status` to the multipart request when you follow the steps in xref:exchange-api.adoc[Publish Assets Using the Exchange API]. If the state is not specified, the asset is created with the default `stable` state.

REST API asset example:



== See Also

* xref:to-delete-asset.adoc[Delete an Asset]
* xref:exchange-api.adoc[Publish Assets Using the Exchange API]
