= Metrics for a Specific Asset and Version
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Administrators and asset owners with contributor permission can view usage details for a specific API specification and REST API assets and each version on the asset details page. 

The following graphic shows the asset details page with usage and engagement metrics for a REST API asset:
// placeholder for details page asset and version

* Version
+
The version of the asset.
* Created by
+
The name of the person who created this version of the asset.
* Created on
+
The date that the asset was created.
* Lifecycle state
+
Which state the asset is currently in. The states are In Development, Stable, or Deprecated.
* Conformance status
+
Conformance status appears for all REST APIs and AsyncAPIs. Status can be Conformant, Not Conformant, and Not Validated.
* Engagement contribution
+
The engagement contribution is the percentage of usage of the given asset patch or minor version with regards to its respective minor or major version.
* Downloads
+
The number of times the asset was downloaded from Exchange. You can sort by ascending or descending order. 
* Imports from API Designer
+
The number of times the asset was imported into Design Center. You can sort by ascending or descending order.
* Imports from Studio
+
The number of times the asset was imported into Studio. You can sort by ascending or descending order.
* All-time Stats
** Dependents
+
The number of dependent assets since the version was created.
** Contracts
+
The number of approved contracts since the version was created.


== Viewing Asset Version Engagement
To view usage and engagement metrics for the asset versions of API Specification Fragments and REST APIs:

. In the Exchange catalog, select an API Specification or REST API.
+
The asset details page displays the asset metadata.
. In the navigation bar, click *Asset versions engagement*.
// screen capture for Asset versions engagement in nav bar
+
The Asset versions engagement page displays.

. To filter by date, select a date range from 7 days, 30 days, or 60 days.
+
The default date range is the last 7 days.
. To export the usage data, click Export to CSV.
