= Public Portal Vanity Domain
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

This document contains instructions and the necessary NGINX configuration for setting up an organization's public portal using a vanity domain.

== Whitelist Your Domain

Your domain needs to be whitelisted in Exchange for your public portal to work properly. To do so:

. Get an access token from an Anypoint Platform user account that has the Organization Administrator role in the master organization:
+
[source,console]
----
ACCESS_TOKEN=$(curl https://anypoint.mulesoft.com/accounts/login -XPOST -d "username=YOUR_USERNAME&password=YOUR_PASSWORD" | jq -r ".access_token")
----
+
. Use the access token to whitelist your custom domain:
+
[source,console]
----
curl https://anypoint.mulesoft.com/exchange/api/v1/organizations/YOUR_ORGANIZATION_DOMAIN/portal/domain -XPUT -d "your.custom.domain" -H "content-type: text/plain" -H "authorization: bearer $ACCESS_TOKEN"
----
+
IMPORTANT: If this step is not followed, you won't be able to log in to the portal or perform any actions that need authentication.

== Set up a reverse proxy

A reverse proxy allows users to access and navigate the vanity domain site exactly as if they were at the MuleSoft site. For example, users could access and navigate `+https://developers.robocop.com/path/of/justice/+` exactly as if they were at `+https://anypoint.mulesoft.com/exchange/portals/robo-cop/+`.

This can be achieved through a https://en.wikipedia.org/wiki/Reverse_proxy[reverse proxy] that reroutes requests to your specific domain to the Anypoint Platform. In the following section, we provide example minimal NGINX configuration rules needed to implement the reverse proxy correctly.

You can set up the reverse proxy on servers other than NGINX, including Apache, content delivery networks (CDNs), and many more. The specific configuration needed for your current web server implementation may need to vary slightly, but the rules should be implemented in the same way.

=== Generic configuration

A basic reverse proxy for a portal Vanity Domain configuration needs:

. Routes mapping

. Custom headers 

==== Routes mapping

First you need to setup static resources routes mapping for ‘shared’, ‘icons’, ‘exchange/api-console-components’ and ‘node_modules’. This routes need to be at root level regardless your portal path.

For example

`+https://developers.robocop.com/shared+` needs to be rerouted to `+https://anypoint.mulesoft.com/shared+`

`+https://developers.robocop.com/icons+` needs to be rerouted to `+https://anypoint.mulesoft.com/icons+`

`+https://developers.robocop.com/node_modules+` needs to be rerouted to `+https://anypoint.mulesoft.com/node_modules+`

`+https://developers.robocop.com/api-console-components+` needs to be rerouted to `+https://anypoint.mulesoft.com/api-console-components+`




Then you need to route 'callback' root route to  `+https://anypoint.mulesoft.com/exchange/portals/+**{YOUR_ORGANIZATION_DOMAIN}**/callback`

For example

`+https://developers.robocop.com/callback+` to `+https://anypoint.mulesoft.com/exchange/portals/robo-cop/callback+`

After that, you need to route all your portal traffic to the Anypoint Platform.

For example

`+https://developers.robocop.com/path/of/justice/+` *_(and all routes under this path)_*
To 
`/https://anypoint.mulesoft.com/exchange/portals/robo-cop/`

NOTE: For this example ‘path/of/justice/’ was set as your portal path, but it can be any path you want.

==== Custom headers

Finally you need to add some headers for each one of the routes described above.

[source,console,linenums]
----
‘X-Forwarded-Path’ with your public portal path, Eg ‘path/of/justice/’. This path must end with a slash “/“.
‘X-Forwarded-Host’ with your hostname, Eg ‘developers.robocop.com’
----

=== Using NGINX

[source,console,linenums]
----
location ~ /(shared|node_modules|icons|exchange/api-console-components) {
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Path ${PUBLIC_PORTAL_PATH};

    proxy_pass ${ANYPOINT_BASE_URL};
}

location /callback {
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Path ${PUBLIC_PORTAL_PATH};

    proxy_pass ${ANYPOINT_BASE_URL}/exchange/portals/${ORGANIZATION_DOMAIN}/callback;
}

location ${PUBLIC_PORTAL_PATH} {
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Path ${PUBLIC_PORTAL_PATH};

    proxy_pass ${ANYPOINT_BASE_URL}/exchange/portals/${ORGANIZATION_DOMAIN}/;
}
----

With:

[source,console,linenums]
----
${PUBLIC_PORTAL_PATH}: Your custom path. Must end with a forward slash "/".
${ANYPOINT_BASE_URL}: Anypoint Platform URL for the desired region.
${ORGANIZATION_DOMAIN}: Your organization's domain in Anypoint Platform.
----

For example, for the `Robocop` organization public portal with an Anypoint Platform domain of `robo-cop` to run on `+developers.robocop.com/path/of/justice/+`:

[source,console,linenums]
----
${PUBLIC_PORTAL_PATH}: /path/of/justice/
${ANYPOINT_BASE_URL}: https://anypoint.mulesoft.com
${ORGANIZATION_DOMAIN}: robo-cop
----

NOTE: Your server must run using `https`.

If set up correctly, you can access and navigate to `+https://developers.robocop.com/path/of/justice/+` exactly as if you were at `+https://anypoint.mulesoft.com/exchange/portals/robo-cop/+`.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
