= Configure API Instances
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Use Anypoint Exchange to configure whether REST, SOAP, and HTTP API services are public or private in a private Exchange or in an Exchange portal. For example, configure public or private visibility for proxies or policies associated with your API and set using API Manager.

After you register an API from Exchange in API Manager, the instances for the API appear in Exchange in the API instances list in the navigation bar.

Exchange also creates API instances for APIs managed by another API management program outside of Anypoint Platform.

Access differs by Exchange type. In a private Exchange, the API instances list appears for HTTP, REST, and SOAP APIs. In an Exchange portal, the API instances list appears for SOAP and HTTP APIs. All instances in an Exchange portal are read only.

Visibility for each instance is either private or public. All users in a business group's Exchange portal can see a public instance. Users can see a private instance if the asset is shared with them or if they have an Anypoint Platform permission that grants access.

In a private Exchange, asset administrators have access to change the visibility of API instances and add new instances. Make an instance public with the visibility indicator. Edit the instance with the pencil icon. Delete the instance with the X icon.

REST APIs provide a mocking service with data to test API features. The mocking service is always public.

== See Also

* xref:design-center::design-mocking-service.adoc[Simulate Calls to an API]
