= Delete an Asset
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can delete an asset in the first seven days of its creation and reuse that asset's name, group, asset ID, and version. A delete within the first seven days is known as a _hard delete_.

If you delete the asset after seven days, you can't reuse its name, business group name, account ID, and version.
A delete after seven days is known as a _soft delete_. After seven days, if you want to reuse the asset name,
choose a new version number or put the asset in a different business group.

After a hard delete or a soft delete, an asset cannot be recovered or undeleted.

If you try to delete an asset version with dependent assets, Exchange shows a warning. Remove the dependencies and then delete the asset version.

If you try to delete an API or policy asset version with dependent API instances, Exchange shows a warning. Remove the dependencies and then delete the asset version. The *API instances* page displays each API asset's instances.

You cannot delete a policy asset that is applied to any managed API instances. On the policy asset's page, the *APIs using this policy* tab shows which API instances have that policy applied. Use API Manager to remove the policy from the instances, and then delete the policy.

To delete a patch version of an asset:

. In the asset details pane, click *Manage versions*.
. Click the three dots menu and select *Delete version*.

To delete an entire asset, delete all of its patch versions.

== See Also

* xref:to-deprecate-asset.adoc[To Deprecate an Asset]
* xref:to-change-raml-version.adoc[To Change a RAML Version]
