= Deleting an Asset
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Keep your asset catalog maintained by deleting outdated or redundant assets. This makes it easier for consumers to find and reuse the assets they need. 

When deleting assets, admins determine if the GAV (group ID, asset ID, and version) information of the deleted asset can be reused for a different asset. Therefore, when you delete an asset, you might not be able to reuse its GAV.

After deleting an asset, it can't be recovered or undeleted.

If you try to delete an asset version with dependent assets, Exchange shows a warning. Remove the dependencies and then delete the asset version.

If you try to delete an API or policy asset version with dependent API instances, Exchange shows a warning. Remove the dependencies and then delete the asset version. The *API instances* page displays each API asset's instances.

You can't delete a policy asset that is applied to any managed API instances. On the policy asset's page, the *APIs using this policy* tab shows which API instances have that policy applied. Use API Manager to remove the policy from the instances, and then delete the policy.

To delete a patch version of an asset:

. In the asset details, click *View versions*.
. Click the three dots menu and select *Delete version*.
+
When GAV reuse is enabled, you have a option to reuse the GAV. If you don't select this option, the asset version's GAV will be deleted and can't be reused. If you select this option, the asset version's GAV can be reused.
. Click *Delete*.

To delete an entire asset, delete all of its patch versions.

== Restore a Deleted Asset
You can restore assets that were deleted along with their GAVs using this endpoint:

`/api/v2/organizations/:organizationId/softDeleted`

It is not possible to recover deleted assets if their GAV information have been reassigned to a different asset.


== See Also

* xref:to-change-raml-version.adoc[To Change a RAML Version]
