= To Manage Portal Resources in Exchange
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Before starting

To manage portal resources using the Exchange Experience API, login to the Anypoint Platform and obtain an authentication token. Make every request with the header `Authorization: bearer ACCESS_TOKEN`:

+
[source,console]
----
ACCESS_TOKEN=$(curl https://anypoint.mulesoft.com/accounts/login -XPOST -d "username=YOUR_USERNAME&password=YOUR_PASSWORD" | jq -r ".access_token")
----
+

== Deleting Asset Portal images
The number of resources that can be uploaded to an asset's portal is currently limited to 100 items. Attempting to add another image after reaching the limit will result in an error. In order to allow for more images to be created, you can consult the existing uploaded images and delete them by using the Exchange Experience API.

To list all resources of an asset portal:
    GET https://anypoint.mulesoft.com/exchange/api/v2/assets/:groupId/:assetId/:version/portal/draft/resources

To get a specific resource of an asset portal:
    GET https://anypoint.mulesoft.com/exchange/api/v2/assets/:groupId/:assetId/:version/portal/draft/resources/:resourceId

To delete a specific resource of an asset portal:
    DELETE https://anypoint.mulesoft.com/exchange/api/v2/assets/:groupId/:assetId/:version/portal/draft/resources/:resourceId

With:
    groupId: The asset's groupId
    assetId: The asset's assetId
    version: The asset's version
    resourceId: The image file name.

== Deleting Public Portal images
In the case of the organization's Public Portal, all images uploaded are subject to the 100 item limit. You can also list and delete existing resources by using the Exchange Experience API:

To list all resources of the public portal:
    GET https://anypoint.mulesoft.com/exchange/api/v2/portals/:organizationDomain/draft/resources/

To get a specific resource of the public portal:
    GET https://anypoint.mulesoft.com/exchange/api/v2/portals/:organizationDomain/draft/resources/:resourceId

To delete a specific resource of the public portal:
    DELETE https://anypoint.mulesoft.com/exchange/api/v2/portals/:organizationDomain/draft/resources/:resourceId

With:
    organizationDomain: Your organization's domain
    resourceId: The image file name.
