= Share an Asset
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/
:page-aliases: to-share-an-asset-with-a-user.adoc

Exchange administrators can share an asset with another user or with a team in a separate organization.

== Share With a User

If the person is not in your organization,
click Access Management > Users to add them.

. Click an asset to show its details and click Share.
. In the Share menu, type a few letters of the person's name you want to share this asset with.
Or click a filter to list only users who have Viewer, Contributor, or Admin rights.
. Click Add.
. Repeat steps 2 and 3 to add additional users to share the asset with.

You can also use the Share menu to change who you are sharing the asset with or to stop sharing with one or more users.

== Share With an External Team

Exchange administrators can grant viewer access for an asset in their organization to teams in other organizations.

The organization granting viewer access is the granting organization, and the organization that includes the teams receiving access is the receiving organization.

. The receiving organization adds the granting organization to its list of trusted organizations in Anypoint Access Management, as described in xref:access-management::external-org-access.adoc[External Organization Access].
+
Assets can only be shared with teams in another organization if that organization has enabled receiving viewer access to assets from external organizations.
+
. The granting organization adds the receiving organization to its list of trusted organizations in Anypoint Access Management, as described in xref:access-management::external-org-access.adoc[External Organization Access].
+
Receiving teams only appear in the Share menu if both organizations have added the other.
+
. Login to your Exchange administrator account in the granting organization.
. Click an asset to show its details and click Share.
. In the Share menu, begin typing the name of the team you want to share the asset with.
. Select the team you want to grant viewer access to.
. Repeat steps 5 and 6 to add additional teams to share the asset with.

You can also use the Share menu to change who you are sharing the asset with or to stop sharing with one or more teams.

When the administrator grants viewer access to the asset, Exchange sends an email notification to the team maintainer of each receiving team.

Any Exchange user can click the *Shared with me* link in the left navigation menu of Exchange to show all assets shared with their user account and all assets shared with any of their teams.

Only internal users can request access to an API or gain the contributor or administrator roles. To grant these permissions to a user from another organization, invite the user to become an internal user of your organization, and then grant the contributor, administrator, or API access requestor permissions.

== See Also

* xref:access-management::external-org-access.adoc[Access Management External Organization Access]
