= Sharing an API Asset to a Public Portal
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

. Click an API asset to show its details.
. Click Share and click *Add to the public portal*.
. (Optional) Click Share Internally if you decide to not put the asset in the public portal and instead return
to the previous Share menu.
. (Optional) Click API Instances to manage instance visibility before proceeding. After following this link, you are
returned to the previous Share menu.
. Click the version of the asset you want to publish in the public portal.
. Click Share. If no action occurs when you click Share, refresh your browser and log in again to repeat sharing the asset.

A public portal is visible to anyone on the internet who has the URL of the portal. The URL for a public portal starts with `+https://anypoint.mulesoft.com/exchange/portals/ORGANIZATION_NAME/+`. To remove an asset from a public portal, you need to make the asset
private as described in the next section.

== Removing an Asset from a Public Portal

*Note:* This procedure only takes the asset out of a portal. It doesn't delete the asset.

. Click the asset in Exchange and click Share.
. Click Add to the Public Portal.
. Click the version field checkbox to uncheck the field.
. Click Share.
. In Exchange, refresh the browser screen and you can see that the Visibility
setting in the asset's Overview has changed to Private.

== See Also

* xref:about-portals.adoc[Working With Exchange Public Portals]