= Publish an API to a Public Portal
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Use your organization's public portal to publish API assets for viewing and use by developers inside and outside your organization.

A public portal is visible to anyone who has the URL of the portal. The URL for a public portal starts with `+https://anypoint.mulesoft.com/exchange/portals/Domain_Name/+`.

Replace `Domain_Name` with the domain name shown in Anypoint access management on the xref:access-management::organization.adoc#organization-page[*Organization* page].

== Permissions to Control Asset Publishing

An organization's Exchange administrators add assets to the public portal and remove assets from the public portal.

Grant the Exchange administrator permission to a user or revoke the permission from a user with Anypoint Access Management.

For more information see xref:to-set-permissions.adoc[Set User Access Permissions].

== Add an Asset to a Public Portal

Follow these steps to add an asset to a portal and make the asset public.

Adding an asset to a portal does not delete the asset. It is still available internally.

. Select an API asset to show its details.
. Select *Share* and choose *Public Publish it on the public portal*.
. Select the version of the asset you want to publish in the public portal.
. Select *Save*.

If no action occurs, refresh your browser, log in again, and add the asset again.

== Remove an Asset from a Public Portal

Follow these steps to remove an asset from a portal and make the asset private.

Removing an asset from a portal does not delete the asset. It is still available internally.

. Select the asset in Exchange and click *Share*.
. Select *Public - Publish in the on the public portal*.
. Unselect the version checkbox.
+
The version of the asset is set to *Private*.
+

. Select *Save*.
. In Exchange, refresh the browser screen.
+
In the asset's *Overview* the *Visibility* setting is now *Private*.

== See Also

* xref:about-portals.adoc[Public Portals]
* xref:to-set-permissions.adoc[Set User Access Permissions]
