= Share an API Asset to a Public Portal
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

You can use your organization's public portal to share API assets publicly. Developers inside and outside your organization can access the assets on the public portal.

A public portal is visible to anyone who has the URL of the portal. The URL for a public portal starts with `+https://anypoint.mulesoft.com/exchange/portals/ORGANIZATION_NAME/+`.

== Permissions to Control Asset Sharing

An organization's Exchange administrators control whether each API asset created in the organization is shared in the public portal by adding assets to the public portal and removing assets from the public portal.

Grant the Exchange administrator role to a user or revoke the role from a user with the *Access Management* -> *Roles* menu.

For more information see xref:to-set-permissions.adoc[Set User Access Permissions].

== Add an Asset to a Public Portal

Follow these steps to add an asset to a portal and make the asset public.

Adding an asset to a portal does not delete the asset. It is still available internally.

. Select an API asset to show its details.
. Select *Share* -> *Add to the public portal*.
. (Optional) If you decide not to put the asset in the public portal, select *Share Internally* to return to the previous *Share* menu.
. (Optional) If you wish to manage instance visibility before proceeding, select *API Instances*. After following this link, you are returned to the previous *Share* menu.
. Select the version of the asset you want to publish in the public portal.
. Select *Share*.

If no action occurs, refresh your browser, log in again, and share the asset again.

== Remove an Asset from a Public Portal

Follow these steps to remove an asset from a portal and make the asset private.

Removing an asset from a portal does not delete the asset. It is still available internally.

. Select the asset in Exchange and select *Share* -> *Add to the Public Portal*.
. Uncheck the version field checkbox.
. Select *Share*.
. In Exchange, refresh the browser screen.
. In the asset's *Overview* the *Visibility* setting is now *Private*.

== See Also

* xref:about-portals.adoc[Public Portals]
* xref:to-set-permissions.adoc[Set User Access Permissions]
