= Share an Asset
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/
:page-aliases: to-share-an-asset-with-a-user.adoc

Exchange administrators and asset administrators can share an asset with another user or team in their organization, with the whole organization, or with an external organization.

Any Exchange user can click the *Shared with me* link in the left navigation menu of Exchange to show all assets shared with their user account and all assets shared with their organization.

== Share Assets with a User

. If a user that you want to share an asset with is not in your organization, click *Access Management* > *Users* to add them to your organization.
. Click an asset to show its details.
. Click *Share*.
. Begin typing the name of the person you want to have access to this asset.
. Select that person in the list.
. Select whether to grant the user viewer, contributor, or administrator rights.
. Add any additional users.
. Click *Save*.

You can also click *Share* to change who you are sharing the asset with or to stop sharing with one or more users.

== Share Assets with a Team

. Click an asset to show its details.
. Click *Share*.
. Begin typing the name of the team you want to have access to this asset.
. Select that team in the list.
. Select whether to grant the team viewer, contributor, or administrator rights.
. Add any additional teams.
. Click *Save*.

To add and remove users on a team, or grant a team viewer, contributor, or administrator access to all assets in a business group, use the xref:access-management::teams.adoc[teams settings in Anypoint Access Management].

== Share Assets with Your Organization

Exchange administrators and asset administrators can share an asset with everyone in their organization.

. Click an asset to show its details.
. Click *Share*.
. Begin typing the name of your organization.
. Select the list item for everyone at your organization.
. Select whether to grant all members of your organization viewer, contributor, or administrator rights.
. Click *Save*.

When an asset is shared with an organization, email notification is sent to the organization administrators.

You can also click *Share* to stop sharing the asset with everyone at your organization.

== Share Assets with an External Organization

Exchange administrators and asset administrators can grant viewer access to an asset to everyone in a chosen external organization.

The granting organization holds an asset and grants viewer access to that asset to the receiving organization.

To grant viewer access to an asset to an external organization:

. Each of the granting organization and the receiving organization adds the other to its External Access list in Anypoint Access Management, as described in xref:access-management::external-organization-access.adoc[External Organization Access].
+
Assets can be shared with another organization only if that organization has enabled receiving viewer access to assets from external organizations.
. Log in to your Exchange administrator or asset administrator account in the granting organization.
. Click the asset to show its details.
. Click *Share*.
. Begin typing the name of the external organization you want to share this asset with.
. Select the organization in the list.
. Repeat steps 5 and 6 to share with additional organizations.
. Click *Save*.

When an asset is shared with an organization, email notification is sent to the organization administrators.

You can also click *Share* to change who you are sharing the asset with or to stop sharing with one or more organizations.

Only internal users in the granting organization can request access to an API or gain the contributor or administrator permissions.

=== Using Assets Shared by a Granting Organization

A user in a receiving organization can use Studio or Flow Designer to search for a shared connector, configure it, and use it in a Mule application.

A user in a receiving organization can use Studio or Flow Designer to implement a Mule application based on a shared example or template.

A user in a receiving organization cannot use API Manager to manage a shared REST, SOAP, or HTTP API that was created in Exchange in the granting organization. API Manager only shows APIs from the user's business group. However, the user can use the API in Studio in the flow as a source for scaffolding an application.

A user in a receiving organization cannot use API Manager to apply a shared custom policy that was uploaded to Exchange in the granting organization. API Manager does not show policies shared by granting organizations in the list of policies that can be applied to an API instance.

A user in a receiving organization can use API Designer to import a shared RAML fragment that was created in Design Center in the granting organization. The user can also add the fragment as a dependency in a new API specification. If the granting organization stops sharing the fragment or deletes the fragment, then the API specification shows the error "File not found."

== See Also

* xref:access-management::external-organization-access.adoc[Access Management External Organization Access]
