= Using API Catalog CLI

After you have installed the API Catalog CLI and configured permissions, you can use the API Catalog CLI commands to autocatalog your APIs.

//Command summary start

[[api-catalog-commands]]
== API Catalog Commands

API Catalog CLI includes the following commands:

include::partial$api-catalog.adoc[tag=summary]

//Command summary end

== View Command Help

Use the help option to list the commands or command options and their descriptions. The following examples show how the help option is used with each of the commands:

----
api-catalog --help
api-catalog autocomplete --help
api-catalog create-descriptor --help
api-catalog publish-asset --help
----

NOTE: You can optionally configure the `api-catalog autocomplete` command so that you can use the tab key with a partially typed command to autocomplete it. See xref:configure-cli-autocomplete.adoc[Configure Command Autocompletion] for more details.

//Common Options start

include::partial$api-catalog.adoc[tag=common-options]

//Common Options end

[[authentication]]
== Authentication

// Authentication start

include::partial$cli-auth.adoc[tag=summary]

include::partial$cli-auth.adoc[tag=sso]

include::partial$cli-auth.adoc[tag=conffile]

include::partial$cli-auth.adoc[tag=cmdline]

include::partial$cli-auth.adoc[tag=envvars]

// Authentication end 