= View GraphQL API Schema and Run Queries
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

The GraphQL console is an easy-to-use interface for API app developers to interact with GraphQL APIs in Exchange. GraphQL APIs are schema definitions that contain the object types and definitions that are used to interact with the API through the GraphQL specification. The GraphQL console enables app developers to query an API that supports this language in a much more flexible way than REST. The console supports standard GraphQL query syntax. From the console, explore and understand the available GraphQL schemas and write, run, and troubleshoot GraphQL queries. The console is located in the asset details page.

(placeholder for screen capture of the console and callouts)

The console uses panels for viewing schemas, writing queries, and reviewing query results. These panels can be resized.

* Schema panel: Use the Schema panel to explore the 
* GraphQL API schema types
* Queries panel:
* Results panel

== Before You Begin

To use the GraphQL console, you must have the Exchange Viewer permission. For more information, see xref:to-set-permissions.adoc[Set User Access Permissions].

== View GraphQL API Schemas

Explore the schema by inspecting the types, fields, and relationships defined in the schema to see a visual representation of the data and operations. Use the Schema explorer panel to inspect the query methods that are available for the API schema. 



The documentation explorer renders the information and allows us to navigate the documentation of
the API

The outline panel renders the information in a neater way

Turn the query builder, put the doc first then the query builder

You can search the schema documentation to find relevant information about specific types, fields, or operations. Use the *Schema* panel to 

. In the Exchange landing page, click the *Any type* filter and select GraphQL APIs from the list.
. Click a GraphQL API from the results.
. In the navigation bar, click *Console*.
. In the *Schema* panel, review the schema documentation.
. To search the schema documentation for specific information, enter a keyword in the *Search* box. For example, a field or type.

== Run a GraphQL Query
Use the query editor to write queries into the console and run them in real-time. The query builder enables you to add data to the query by selecting from a list to execute the query. Use the query builder to write queries without knowing the specific syntax. The console provides immediate feedback, displaying the results of the query and any errors. The query editor is located in the Query panel. To run queries, a GraphQL server is required to query between the API instance.

. In the query editor of the GraphQl console, start typing your query using the in-line autocomplete function or press Control + Space to add types.
. Add any query variables you want to use in the Query Variables pane.
. From the Instance selector, select an available server instance that you want to use. If there are no servers available, the Instance selector is disabled.
. To add a new a non-managed instance, click *Add new instance*.
. From non-managed instances, click *Add new instance*.
. Enter the name and URL of the instance and click the check icon.
. Click *Execute*.
. Validate the query results in the *Results* panel.




