= Authentication

// tag::summary[]

To authenticate to Anypoint Platform while running the API Catalog CLI, you must use one of the authentication option combinations:

* Username and password
* Client ID and client secret
* Bearer token (command line only)

You must also specify host, environment, and organization unless you are logging in to the defaults.

You can pass Anypoint Platform credentials using the following methods:

* <<single-signon,Using single signon (SSO)>>
* <<credentials-file,Using a credentials configuration file>>
* <<command-line-options,Using command line options>>
* <<env-variables,Using environment variables>>

Configuration settings are overridden as follows:

* Command line options override all other methods. 

* Environment variables are used if command line options are not specified and override any credentials configuration file settings.

* Credentials configuration file options are used if no command line options or environment variables are set.

// end::summary[]

// tag::sso[]

[[single-signon]]
== SSO

If you have configured Anypoint Platform to use SSO with the system on which you are running API Catalog CLI, run the API Catalog CLI command with no credential options and it logs in to Anypoint Platform through SSO. For information on configuring login through SSO, see xref:access-management::external-identity.adoc[About Identity Management].

// end::sso[]

// tag::conffile[]

[[credentials-file]]
== Credentials Configuration File

If you are not using SSO, the most secure way to pass credentials to your Anypoint Platform CLI installation is through the credentials configuration file.  

You can authenticate to Anypoint Platform by running the `api-catalog` command with the `conf` option to add your credentials to a configuration file. After you have created the configuration file with valid credentials, you can run the `api-catalog` commands without specifying any credentials options and the authentication is done using the configuration file values. 

You can set authentication values in the configuration file using a combination of the following authentication keys:

----
username
password
client_id
client_secret
host
environment
organization
----

To create your configuration file:

* Run the `api-catalog conf` command with the key value pair you want to use. For example, the following command sets the username and password:
+
----
$ api-catalog conf username myuser
$ api-catalog conf password mypwd
----

The commands store the credential information in the `config.json` file in the following locations:

* MacOS: `~/Library/Preferences/@mulesoft/api-catalog-cli-nodejs/config.json`

* Windows: `%LOCALAPPDATA%\mycli`

* Unix: `~/.config/mycli`

*Examples:*

* Set a value for a bearer token: 
+
----
$ api-catalog conf bearer b71cab22-e5cc-43c4-90ed-5a1124b6ae1f
----
+
* Set values for username and password: 
+
----
$ api-catalog conf username myuser
$ api-catalog conf password mypwd
----
+
* Set values for a specific host, organization, and environment:
+
----
$ api-catalog conf host myco.anypoint.mulesoft.com
$ api-catalog conf environment ec7d16cb-43fd-4796-8b4f-5cff7294fcf9
$ api-catalog conf organization 8a840abc-e63a-4f8d-87ad-24052eda3018
----
+
* Set values for client ID and client secret:
+
----
$ api-catalog conf client_id myClientID
$ api-catalog conf client_secret myCLientSecret
----

Example `config.json` contents after running the above commands:

----
 {
	"bearer": "b71cab22-e5cc-43c4-90ed-5a1124b6ae1f",
    "username": "myuser",
	"password": "mypwd",
    "host": "myco.anypoint.mulesoft.com",
	"environment": "ec7d16cb-43fd-4796-8b4f-5cff7294fcf9",
	"organization": "8a840abc-e63a-4f8d-87ad-24052eda3018",
	"client_id": "1787c36ab544466698e380131040faad",
	"client_secret": "2dA616efca1E4181A2A77BBF046868BE"
 }
----

// end::conffile[]

// tag::cmdline[]

[[command-line-options]]
== Command Line Options

You can authenticate to Anypoint Platform through command line by running the `api-catalog` command with a combination of the following options:

----
--username
--password
--client_id
--client_secret
--bearer
--organization
--environment
----

*Examples:*

* Authenticate on the command line using username and password
+
----
$ api-catalog --username myUserName --password myPassword --organization=myOrgId account:environment:list
----

* Authenticate on the command line  using client ID and client secret
+
----
$ api-catalog --client_id myClientID myClientSecret --organization=myOrgId account:environment:list
----

* Authenticate on the command line  using a bearer token
+
You can generate a bearer token in Anypoint Platform and pass it to API Catalog CLI directly. When you provide a bearer token, API Catalog CLI ignores any provided user or client credentials.
+
----
$ api-catalog --bearer myBearerToken --organization=myOrgId account:environment:list
----
+
Your Anypoint Platform session expires when the bearer token expires.
+
For information about generating a bearer token, see https://help.mulesoft.com/s/article/How-to-generate-your-Authorization-Bearer-token-for-Anypoint-Platform[How to Generate Your Authorization Bearer Token for Anypoint Platform].

// end::cmdline[]

// tag::envvars[]

[[env-variables]]
== Environment Variables

You can authenticate to Anypoint Platform by setting a combination of the following environment variables before running an `api-catalog` command:

----
ANYPOINT_USERNAME
ANYPOINT_PASSWORD
ANYPOINT_CLIENT_ID
ANYPOINT_CLIENT_SECRET
ANYPOINT_ORG
ANYPOINT_ENV
ANYPOINT_HOST
----

*Examples:*

* Authenticate by setting the environment variables for username and password
+
----
$ export ANYPOINT_USERNAME=myUserName
$ export ANYPOINT_PASSWORD=myPassword
$ export ANYPOINT_ORG=myOrgId
----

* Authenticate by setting the environment variables for client ID and client secret
+
----
$ export ANYPOINT_CLIENT_ID=myClientID
$ export ANYPOINT_CLIENT_SECRET=myCLientSecret
$ export ANYPOINT_ORG=myOrgId
----

// end::envvars[]